/**
 * Contextual AI suggestions.
 *
 * Given the selected node's kind, produce a small set of relevant motion
 * suggestions (spec §AI Philosophy: "Select Logo → Reveal, Premium Motion…").
 *
 * CRITICAL RULE (spec): everything generated by AI must remain editable.
 * Never generate black-box output — applying a suggestion authors real
 * keyframes on the Animation Engine, which then show up in the timeline and
 * can be dragged, retimed, or deleted like any hand-made animation.
 */

import defaultSceneGraph from '@core/scene/DefaultSceneGraph';
import { defaultAnimation } from '@motion/animation';
import { runAnimEdit } from '@core/animation/animationCommands';
import type { SceneKind } from '@core/scene/seedDefaultScene';
import type { IconName } from '@components/Icon';

/** Read a node's current base value for a numeric prop (scans components). */
export function readNodeProp(nodeId: string, prop: string): number | undefined {
  const node = defaultSceneGraph.getNode(nodeId);
  if (!node) return undefined;
  for (const c of node.components) {
    const v = (c.props as Record<string, unknown>)[prop];
    if (typeof v === 'number') return v;
  }
  return undefined;
}

export interface AiSuggestion {
  /** Stable per (kind, action) — used as the per-asset dismissal key. */
  id: string;
  label: string;
  description: string;
  icon: IconName;
  /** Author editable keyframes on the node, anchored at `atTime` (seconds). */
  apply: (nodeId: string, atTime: number) => void;
}

/** Author a scalar keyframe (thin wrapper; emits AnimationChanged). */
function key(nodeId: string, prop: string, t: number, value: number): void {
  defaultAnimation.setKeyframe(nodeId, prop, t, value);
}

/**
 * The action library. Each entry authors a short, fully-editable animation.
 * Values are absolute and read the node's current base so the motion starts
 * from where the layer already is.
 */
const ACTIONS: Record<string, AiSuggestion> = {
  reveal: {
    id: 'reveal',
    label: 'Reveal',
    description: 'Fade and rise into view',
    icon: 'sparkles',
    apply: (nodeId, t) => {
      const y = readNodeProp(nodeId, 'y') ?? 0;
      key(nodeId, 'opacity', t, 0);
      key(nodeId, 'opacity', t + 0.6, 100);
      key(nodeId, 'y', t, y + 24);
      key(nodeId, 'y', t + 0.6, y);
    },
  },
  spin: {
    id: 'spin',
    label: 'Premium Spin',
    description: 'A full, smooth rotation',
    icon: 'refresh',
    apply: (nodeId, t) => {
      const r = readNodeProp(nodeId, 'rotation') ?? 0;
      key(nodeId, 'rotation', t, r);
      key(nodeId, 'rotation', t + 1, r + 360);
    },
  },
  float: {
    id: 'float',
    label: 'Float',
    description: 'A gentle up-and-down drift',
    icon: 'arrow-up',
    apply: (nodeId, t) => {
      const y = readNodeProp(nodeId, 'y') ?? 0;
      key(nodeId, 'y', t, y);
      key(nodeId, 'y', t + 1, y - 16);
      key(nodeId, 'y', t + 2, y);
    },
  },
  pop: {
    id: 'pop',
    label: 'Elastic Pop',
    description: 'A quick, springy entrance',
    icon: 'plus',
    apply: (nodeId, t) => {
      const r = readNodeProp(nodeId, 'rotation') ?? 0;
      key(nodeId, 'opacity', t, 0);
      key(nodeId, 'opacity', t + 0.3, 100);
      key(nodeId, 'rotation', t, r - 8);
      key(nodeId, 'rotation', t + 0.4, r);
    },
  },
  headline: {
    id: 'headline',
    label: 'Headline Animation',
    description: 'Slide up with a soft fade',
    icon: 'type',
    apply: (nodeId, t) => {
      const y = readNodeProp(nodeId, 'y') ?? 0;
      key(nodeId, 'opacity', t, 0);
      key(nodeId, 'opacity', t + 0.5, 100);
      key(nodeId, 'y', t, y + 20);
      key(nodeId, 'y', t + 0.5, y);
    },
  },
};

/** Which suggestions apply to each layer kind (spec-flavored presets). */
const BY_KIND: Record<SceneKind, string[]> = {
  shape: ['reveal', 'spin', 'float', 'pop'],
  image: ['reveal', 'float', 'pop'],
  video: ['reveal', 'float'],
  text: ['headline', 'reveal', 'float'],
  group: ['reveal'],
};

export function suggestionsForKind(kind: SceneKind): AiSuggestion[] {
  return (BY_KIND[kind] ?? []).map((k) => ACTIONS[k]).filter((a): a is AiSuggestion => !!a);
}

/**
 * Apply a suggestion as a single, undoable transaction. The preset authors
 * several keyframes across props; wrapping the whole `apply` in one command
 * means one Cmd+Z reverses the entire suggestion (spec: AI output stays
 * editable AND reversible).
 */
export function applySuggestion(suggestion: AiSuggestion, nodeId: string, atTime: number): void {
  runAnimEdit(`AI: ${suggestion.label}`, () => suggestion.apply(nodeId, atTime));
}
