/**
 * The kill switch is only a kill switch if the key it verifies against is the
 * key the registry actually signs with.
 *
 * Every other revocation test seeds a list through a test seam, so all of them
 * would keep passing with `OPERATOR_PUBLIC_KEY` empty, or holding a typo, or
 * holding the key from a keypair that was regenerated and never redeployed. The
 * failure mode is silent and total in the worst direction: the client refuses
 * every list, which looks exactly like a working client with nothing to revoke,
 * and nobody finds out until the day a takedown has to work.
 *
 * So this file verifies a fixture signed by the REAL operator private key —
 * generated by motion-back `scripts/generate-operator-key.mjs`, signed in the
 * exact shape `RevocationService.signedList` emits. The signature is public
 * information; the private half is not in this repo and never will be. If the
 * operator keypair is rotated, this fixture must be regenerated, and that is
 * the point: the test fails until the pin and the signer agree again.
 */

import { webcrypto } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import {
  acceptRevocationList,
  currentRevocationList,
  isRevoked,
  resetRevocationsForTests,
  OPERATOR_PUBLIC_KEY,
  type SignedRevocationList,
} from './revocation';

// jsdom ships no WebCrypto; `verifyPackageSignature` runs on `crypto.subtle`.
beforeAll(() => {
  if (!globalThis.crypto?.subtle) {
    Object.defineProperty(globalThis, 'crypto', { value: webcrypto, configurable: true });
  }
});

beforeEach(() => resetRevocationsForTests());

const fixture = (): SignedRevocationList =>
  JSON.parse(
    readFileSync(join(__dirname, '__fixtures__', 'operatorSignedList.json'), 'utf8'),
  ) as SignedRevocationList;

describe('the pinned operator key', () => {
  it('is actually pinned', () => {
    /*
      A build shipping an empty key enforces nothing. That is the safe direction
      for a fork, and the wrong one for the app we ship — so it is asserted
      here rather than left to be discovered during an incident.
    */
    expect(OPERATOR_PUBLIC_KEY).not.toBe('');
  });

  it('verifies a list signed by the real operator private key', async () => {
    /*
      The end-to-end proof, and the only test in the suite that would catch a
      pin/signer mismatch. Everything downstream of this — enforcement, the
      mid-session stop, the reinstall refusal — is exercised elsewhere against
      a seeded list, which cannot tell you whether a real one would ever arrive.
    */
    const result = await acceptRevocationList(fixture());

    expect(result.ok).toBe(true);
    expect(currentRevocationList()?.entries).toEqual([
      {
        id: 'studio.acme.exfiltrator',
        reason: 'Uploaded project contents to an undisclosed host.',
      },
    ]);
    expect(isRevoked('studio.acme.exfiltrator', '1.0.0')).toBe(true);
  });

  it('refuses the same list with one byte of the payload changed', async () => {
    // The reason is what the user is shown, so it is the field worth tampering
    // with: an attacker who could edit it could make a takedown read as routine.
    const signed = fixture();
    signed.payload = signed.payload.replace('undisclosed host', 'undisclosed hosts');

    expect(await acceptRevocationList(signed)).toEqual({ ok: false, reason: 'bad-signature' });
    expect(currentRevocationList()).toBeNull();
  });

  it('refuses a well-formed list signed by some other key', async () => {
    /*
      A publisher key is a real, valid, P-256 key that verifies real signatures.
      It is simply not this authority — and an author who could sign a list
      could un-revoke their own plugin and revoke a competitor's.
    */
    const pair = await crypto.subtle.generateKey(
      { name: 'ECDSA', namedCurve: 'P-256' },
      true,
      ['sign', 'verify'],
    );
    const b64 = (b: ArrayBuffer) => Buffer.from(new Uint8Array(b)).toString('base64');

    const payload = JSON.stringify({
      seq: 9_999_999_999_999,
      issuedAt: '2026-08-06T12:00:00.000Z',
      expiresAt: '2999-01-01T00:00:00.000Z',
      entries: [],
    });
    const signature = b64(
      await crypto.subtle.sign(
        { name: 'ECDSA', hash: 'SHA-256' },
        pair.privateKey,
        new TextEncoder().encode(payload),
      ),
    );

    expect(await acceptRevocationList({ payload, signature })).toEqual({
      ok: false,
      reason: 'bad-signature',
    });
  });

  it('refuses everything when a build pins no key at all', async () => {
    /*
      Still the safe direction, and still worth an assertion now that the
      shipped constant is non-empty: an unsigned kill switch is one anybody can
      pull. This is the branch a self-hosted or forked build lands on.
    */
    expect(await acceptRevocationList(fixture(), '')).toEqual({
      ok: false,
      reason: 'no-operator-key',
    });
  });
});

describe('the key stays pinned', () => {
  it('is never supplied by a caller outside tests', () => {
    /*
      `acceptRevocationList` takes the key as a defaulted parameter so the
      no-key branch above stays reachable. That parameter is one refactor away
      from being the hole the pin exists to close — a call site that passes a
      key fetched from the server has re-invented "the server chooses the key".

      So the source is swept. If this fires, the fix is to delete the argument,
      not to widen the sweep.
    */
    const files = listSourceFiles(join(__dirname, '..', '..'));
    const offenders: string[] = [];

    for (const file of files) {
      if (/\.test\.tsx?$/.test(file)) continue;
      const text = stripComments(readFileSync(file, 'utf8'));
      for (const call of callArguments(text, 'acceptRevocationList')) {
        if (hasTopLevelComma(call)) offenders.push(file);
      }
    }

    expect(offenders).toEqual([]);
  });
});

// ── helpers ──────────────────────────────────────────────────────────────────

function listSourceFiles(root: string): string[] {
  const { readdirSync, statSync } = require('node:fs') as typeof import('node:fs');
  const out: string[] = [];
  const walk = (dir: string) => {
    for (const name of readdirSync(dir)) {
      if (name === 'node_modules' || name === '__fixtures__') continue;
      const full = join(dir, name);
      if (statSync(full).isDirectory()) walk(full);
      else if (/\.tsx?$/.test(name)) out.push(full);
    }
  };
  walk(root);
  return out;
}

/** Strip comments, because this file and `revocation.ts` DISCUSS the call. */
function stripComments(text: string): string {
  return text.replace(/\/\*[\s\S]*?\*\//g, '').replace(/\/\/[^\n]*/g, '');
}

/**
 * Does this argument list separate two arguments?
 *
 * Depth-aware, because `acceptRevocationList(build(a, b))` passes ONE argument
 * and must not be flagged — a guard that cries wolf gets widened, and a widened
 * guard is one nobody reads.
 */
function hasTopLevelComma(args: string): boolean {
  let depth = 0;
  for (const ch of args) {
    if ('([{'.includes(ch)) depth++;
    else if (')]}'.includes(ch)) depth--;
    else if (ch === ',' && depth === 0) return true;
  }
  return false;
}

/** The argument text of each call to `name`, brace-matched. */
function callArguments(text: string, name: string): string[] {
  const out: string[] = [];
  const needle = `${name}(`;
  let from = 0;
  for (;;) {
    const at = text.indexOf(needle, from);
    if (at === -1) return out;

    // The declaration is not a call site. Skipping it by preceding keyword
    // rather than by filename keeps the sweep honest if the function moves.
    if (/\b(function|const|let|var)\s+$/.test(text.slice(Math.max(0, at - 24), at))) {
      from = at + needle.length;
      continue;
    }

    let depth = 0;
    let i = at + needle.length - 1;
    for (; i < text.length; i++) {
      if (text[i] === '(') depth++;
      else if (text[i] === ')') {
        depth--;
        if (depth === 0) break;
      }
    }
    out.push(text.slice(at + needle.length, i));
    from = i + 1;
  }
}
