/**
 * The kill switch, and why it is not an update check.
 *
 * An operator takedown used to reach a user only when they happened to open the
 * plugin manager. That is a kill switch with unbounded delay: a plugin pulled
 * for stealing data keeps running on every machine whose owner has not clicked
 * that menu, which may be never.
 *
 * ── Deliberately NOT built on `POST /plugins/updates` ────────────────────────
 *
 * That endpoint works by uploading the user's installed set, so the server
 * learns exactly which plugins every user has. Revocation must not need that.
 * The client fetches a small signed list and matches it LOCALLY, uploading
 * nothing — so the enforcement mechanism is strictly more private than the
 * update check it sits beside, and the registry cannot learn who runs what by
 * watching revocation traffic.
 *
 * ── What makes the list trustworthy ──────────────────────────────────────────
 *
 * **Signed with an OPERATOR key**, not a publisher key. These are different
 * authorities: a publisher key says "the same author made this package"; the
 * operator key says "the registry says stop running this". A plugin author must
 * not be able to sign a list that un-revokes their own plugin, so the key is
 * pinned in the app and is not the one packages are verified against.
 *
 * **Monotonic sequence number.** Anyone who can serve bytes — a proxy, a
 * compromised CDN, a hostile network — can otherwise replay yesterday's list to
 * un-revoke something. A list whose sequence is lower than the highest seen is
 * refused, and the high-water mark is persisted.
 *
 * **A freshness window.** Without one, an attacker who can BLOCK the fetch pins
 * a client to an old list forever, which is the same attack with less effort.
 * A stale list keeps being enforced and the staleness is surfaced — failing
 * open would make blocking the fetch the whole exploit.
 *
 * **Fetch failure is silent.** Working offline is normal and must not produce
 * an error or delay boot. The last known list keeps applying.
 */

import { verifyPackageSignature } from './registry';

/** One revoked plugin. */
export interface RevocationEntry {
  id: string;
  /**
   * Versions to revoke. Absent means every version.
   *
   * Deliberately explicit rather than a range grammar: a semver range in a
   * security control is a parser, and a parser is somewhere for a bypass to
   * live. An operator revoking three versions lists three.
   */
  versions?: string[];
  /** Shown to the user verbatim. A takedown with no reason reads as a bug. */
  reason: string;
}

export interface RevocationList {
  /** Monotonic. A list at or below the high-water mark is refused. */
  seq: number;
  /** ISO. After this the list is STALE — still enforced, and surfaced. */
  expiresAt: string;
  issuedAt: string;
  entries: RevocationEntry[];
}

export interface SignedRevocationList {
  /** The list, as the exact JSON text that was signed. */
  payload: string;
  /** Detached ECDSA P-256 / SHA-256 signature, IEEE P1363 r||s, base64. */
  signature: string;
}

/**
 * The operator's public key, pinned in the app.
 *
 * Pinned rather than fetched for the obvious reason: a key the server can
 * choose is a key an attacker who controls the server can choose. Rotating it
 * is an app release, which is the correct cost for a control of this weight.
 *
 * Generated by motion-back `scripts/generate-operator-key.mjs`. The private half
 * is `MOTION_REVOCATION_KEY` on the server and exists nowhere else — it is not
 * escrowed, so losing it costs an app release to rotate.
 *
 * The empty-string case below is still handled rather than removed: a build
 * given no key must refuse every list rather than accept any, and that is the
 * branch a fork or a self-hosted build lands on.
 */
export const OPERATOR_PUBLIC_KEY =
  'MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE2Zrt+EZ6T/vYPa0w4AFFdiQf7UGyVBi5S6TPQiSQjTDqFgVyFcEsseMG+rBk/AE/NhWxWYTRE/WInb2Xx4lgqA==';

const STORE_KEY = 'motion-editor.revocations.v1';

interface StoredState {
  seq: number;
  list: RevocationList | null;
  /** When this client last successfully verified a list. */
  fetchedAt: string | null;
}

function read(): StoredState {
  try {
    const raw = localStorage.getItem(STORE_KEY);
    if (!raw) return { seq: 0, list: null, fetchedAt: null };
    const parsed = JSON.parse(raw) as StoredState;
    return {
      seq: typeof parsed.seq === 'number' ? parsed.seq : 0,
      list: parsed.list ?? null,
      fetchedAt: parsed.fetchedAt ?? null,
    };
  } catch {
    return { seq: 0, list: null, fetchedAt: null };
  }
}

function write(state: StoredState): void {
  try {
    localStorage.setItem(STORE_KEY, JSON.stringify(state));
  } catch {
    // A hardened profile with no storage. The list still applies for this
    // session; it just will not survive a restart.
  }
}

export type AcceptResult =
  | { ok: true; list: RevocationList }
  | { ok: false; reason: 'no-operator-key' | 'bad-signature' | 'malformed' | 'replay' };

/**
 * Verify a fetched list and adopt it if it is newer.
 *
 * Signature FIRST, then parse — the same order package installation uses, and
 * for the same reason: an unverified payload must never reach a parser.
 *
 * `operatorKey` exists so the no-key branch stays reachable from a test once a
 * key is actually pinned — it is NOT a way to choose the key. The app never
 * passes it, and `revocationKeyIsPinned.test.ts` sweeps the source to keep it
 * that way: a caller that could supply the key is the server choosing the key,
 * which is the whole thing the pin prevents.
 */
export async function acceptRevocationList(
  signed: SignedRevocationList,
  operatorKey: string = OPERATOR_PUBLIC_KEY,
): Promise<AcceptResult> {
  if (!operatorKey) return { ok: false, reason: 'no-operator-key' };
  if (!signed?.payload || !signed?.signature) return { ok: false, reason: 'malformed' };

  const bytes = new TextEncoder().encode(signed.payload);
  const valid = await verifyPackageSignature(bytes, signed.signature, operatorKey);
  if (!valid) return { ok: false, reason: 'bad-signature' };

  let list: RevocationList;
  try {
    list = JSON.parse(signed.payload) as RevocationList;
  } catch {
    return { ok: false, reason: 'malformed' };
  }
  if (typeof list.seq !== 'number' || !Array.isArray(list.entries) || typeof list.expiresAt !== 'string') {
    return { ok: false, reason: 'malformed' };
  }

  const state = read();
  // Refused at or below the mark. Equal counts as a replay: a re-served
  // identical list is harmless, but accepting it would mean the mark never
  // rules anything out.
  if (list.seq < state.seq) return { ok: false, reason: 'replay' };

  write({ seq: Math.max(state.seq, list.seq), list, fetchedAt: new Date().toISOString() });
  return { ok: true, list };
}

/** The list in force right now, from the last successful verification. */
export function currentRevocationList(): RevocationList | null {
  return read().list;
}

/**
 * Is the list past its freshness window?
 *
 * Reported, never acted on by failing open. A client that stopped enforcing a
 * stale list would make "block the fetch" the entire exploit.
 */
export function revocationListIsStale(now = Date.now()): boolean {
  const list = read().list;
  if (!list) return false;
  const expires = Date.parse(list.expiresAt);
  return Number.isFinite(expires) && now > expires;
}

/** Why this plugin is revoked, or null. */
export function revocationFor(pluginId: string, version: string): RevocationEntry | null {
  const list = read().list;
  if (!list) return null;
  for (const entry of list.entries) {
    if (entry.id !== pluginId) continue;
    // No `versions` means every version — the common case for a takedown.
    if (!entry.versions || entry.versions.includes(version)) return entry;
  }
  return null;
}

export function isRevoked(pluginId: string, version: string): boolean {
  return revocationFor(pluginId, version) !== null;
}

/**
 * Fetch the list, verify it, adopt it, and enforce it.
 *
 * Called once at boot, and safe to call again. Everything about it is
 * non-blocking and silent on failure: working offline is normal, and an editor
 * that showed an error or delayed its own startup because a revocation check
 * did not answer would be worse than the problem.
 *
 * The enforcement callback is injected rather than imported so this module
 * stays free of the host — it is the piece that has to be testable without a
 * plugin runtime.
 */
export async function refreshRevocations(
  fetchList: () => Promise<SignedRevocationList | null>,
  enforce: () => void,
): Promise<void> {
  let signed: SignedRevocationList | null = null;
  try {
    signed = await fetchList();
  } catch {
    // Offline, blocked, or the endpoint is not deployed. The last verified list
    // keeps applying — which is why blocking the fetch is not an exploit.
    return;
  }
  if (!signed) return;

  const result = await acceptRevocationList(signed);
  if (!result.ok) {
    // Named in the log, because these are the interesting failures: a bad
    // signature or a replayed sequence number is someone trying something, not
    // a network hiccup.
    if (result.reason !== 'no-operator-key') {
      console.warn(`[plugins] revocation list refused: ${result.reason}`);
    }
    return;
  }

  // Enforced immediately, not at the next restart. A takedown that arrives an
  // hour after the user opened the editor has to land now.
  enforce();
}

/** Test seam. Never called by the app. */
export function resetRevocationsForTests(): void {
  try { localStorage.removeItem(STORE_KEY); } catch { /* ignore */ }
}

/** Test seam: seed a verified list without a signature round trip. */
export function seedRevocationsForTests(list: RevocationList): void {
  write({ seq: list.seq, list, fetchedAt: new Date().toISOString() });
}
