# Embed the renderer WGSL and the material table into the engine (Phase 1 of
# docs/TS_ENGINE_REMOVAL.md: the C++ build reads no TypeScript).
#
#   wgsl/<name>.wgsl   one builtin shader each, verbatim (the exact string handed
#                      to WebGPU / Dawn — never reformat, never re-indent)
#   materials.json     { "shaders": [...], "materials": [...] }
#                        shaders    every builtin shader name, IN ORDER: the
#                                   index is kWgsl<i> in builtin_shaders.inc
#                        materials  every material descriptor (shader, bind-group
#                                   layout, vertex buffers, depth state), in the
#                                   order of `enum class Mat`
#
# premation_embed_wgsl(<out_dir>) writes, at configure time, into <out_dir>:
#
#   builtin_shaders.inc   kBuiltinShaders — included by render_graph/shader_library.cpp
#   materials.inc         enum Mat + kMaterials — included by render_graph/materials.hpp
#   renderer_wgsl.hpp     the C1 prototype's three (textured, blur, vignette)
#
# Every input is a configure dependency, so editing a shader or the table
# re-runs this on the next build. An output is rewritten only when its bytes
# change, so an unrelated reconfigure recompiles nothing.
#
# The emitted text is byte-for-byte what the retired TypeScript extractor wrote
# (below the header comment): raw-string pieces of at most 30,000 UTF-16 code
# units, because -Wpedantic caps a string literal at 65,536 characters.

set(_PREMATION_WGSL_DIR "${CMAKE_CURRENT_LIST_DIR}")

# The C1 prototype header: builtin shader name → C++ identifier.
set(_PREMATION_WGSL_PICK textured kTexturedWgsl blur kBlurWgsl vignette kVignetteWgsl)
set(_PREMATION_WGSL_CHUNK 30000)

# Count of UTF-8 continuation bytes (0x80–0xBF) in `text` → out_cont, and of
# 4-byte lead bytes (0xF0–0xF7, one UTF-16 surrogate pair each) → out_quad.
function(_premation_utf8_counts text out_cont out_quad)
  string(HEX "${text}" hex)
  string(REGEX REPLACE "([0-9a-f][0-9a-f])" "\\1," pairs "${hex}")
  string(REGEX REPLACE "[0-7c-f][0-9a-f]," "" cont "${pairs}")
  string(LENGTH "${cont}" n_cont)
  string(REGEX REPLACE "[0-9a-e][0-9a-f],|f[89a-f]," "" quad "${pairs}")
  string(LENGTH "${quad}" n_quad)
  math(EXPR n_cont "${n_cont} / 3")
  math(EXPR n_quad "${n_quad} / 3")
  set(${out_cont} ${n_cont} PARENT_SCOPE)
  set(${out_quad} ${n_quad} PARENT_SCOPE)
endfunction()

# UTF-16 code units in `text` (complete UTF-8 sequences, or a trailing partial one).
function(_premation_utf16_units text out)
  string(LENGTH "${text}" bytes)
  _premation_utf8_counts("${text}" cont quad)
  math(EXPR units "${bytes} - ${cont} + ${quad}")
  set(${out} ${units} PARENT_SCOPE)
endfunction()

# Split `text` into raw-string literals of at most _PREMATION_WGSL_CHUNK UTF-16
# code units each (the JavaScript `slice` the pieces were first cut with) and
# return them joined by ",\n  ", with the piece count in out_count.
function(_premation_raw_pieces text label out_text out_count)
  string(FIND "${text}" ")WGSL\"" clash)
  if(NOT clash EQUAL -1)
    message(FATAL_ERROR "embed_wgsl: ${label}: the WGSL contains the raw-string delimiter )WGSL\"")
  endif()
  set(pieces "")
  set(count 0)
  set(rest "${text}")
  string(LENGTH "${rest}" rest_bytes)
  while(rest_bytes GREATER 0)
    # A byte count bounds the code-unit count, so only a long text is measured.
    set(rest_units ${rest_bytes})
    if(rest_bytes GREATER _PREMATION_WGSL_CHUNK)
      _premation_utf16_units("${rest}" rest_units)
    endif()
    if(rest_units LESS_EQUAL _PREMATION_WGSL_CHUNK)
      set(piece "${rest}")
      set(rest "")
    else()
      # Grow a byte prefix until it holds CHUNK code units, then take the rest
      # of a multi-byte character the prefix ended inside.
      set(cut ${_PREMATION_WGSL_CHUNK})
      while(TRUE)
        string(SUBSTRING "${rest}" 0 ${cut} head)
        _premation_utf16_units("${head}" units)
        if(units GREATER _PREMATION_WGSL_CHUNK)
          message(FATAL_ERROR "embed_wgsl: ${label}: a surrogate pair straddles a ${_PREMATION_WGSL_CHUNK}-unit piece boundary")
        endif()
        if(units EQUAL _PREMATION_WGSL_CHUNK)
          break()
        endif()
        math(EXPR cut "${cut} + ${_PREMATION_WGSL_CHUNK} - ${units}")
      endwhile()
      while(TRUE)
        string(SUBSTRING "${rest}" ${cut} 1 next)
        string(HEX "${next}" next_hex)
        if(NOT next_hex MATCHES "^[89ab]")
          break()
        endif()
        math(EXPR cut "${cut} + 1")
      endwhile()
      string(SUBSTRING "${rest}" 0 ${cut} piece)
      string(SUBSTRING "${rest}" ${cut} -1 rest)
    endif()
    if(count GREATER 0)
      string(APPEND pieces ",\n  ")
    endif()
    string(APPEND pieces "R\"WGSL(${piece})WGSL\"")
    math(EXPR count "${count} + 1")
    string(LENGTH "${rest}" rest_bytes)
  endwhile()
  if(count EQUAL 0)
    set(pieces "\"\"")
    set(count 1)
  endif()
  set(${out_text} "${pieces}" PARENT_SCOPE)
  set(${out_count} ${count} PARENT_SCOPE)
endfunction()

# Re-run the configure step when any of the given files changes (no-op in -P mode).
function(_premation_configure_depends)
  if(NOT CMAKE_SCRIPT_MODE_FILE)
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS ${ARGN})
  endif()
endfunction()

# Write `content` to `path` only when it differs, so dependents do not rebuild.
function(_premation_write_if_changed path content)
  if(EXISTS "${path}")
    file(READ "${path}" old)
    if(old STREQUAL content)
      return()
    endif()
  endif()
  file(WRITE "${path}" "${content}")
endfunction()

function(premation_embed_wgsl out_dir)
  set(table "${_PREMATION_WGSL_DIR}/materials.json")
  _premation_configure_depends("${table}" "${_PREMATION_WGSL_DIR}/embed_wgsl.cmake")
  file(READ "${table}" json)
  # string(JSON) re-parses its whole input on every call: pull each part out
  # once and query the small pieces.
  string(JSON shader_list GET "${json}" shaders)
  string(JSON mat_list GET "${json}" materials)

  # ── shaders ──────────────────────────────────────────────────────────────
  string(JSON n_shaders LENGTH "${shader_list}")
  if(n_shaders EQUAL 0)
    message(FATAL_ERROR "embed_wgsl: materials.json lists no shaders")
  endif()
  math(EXPR last_shader "${n_shaders} - 1")
  set(header_note "// Regenerated at configure time by native/engine/shaders/embed_wgsl.cmake.\n")
  set(shaders_out "// GENERATED from native/engine/shaders/wgsl/*.wgsl, in the order of\n")
  string(APPEND shaders_out "// native/engine/shaders/materials.json \"shaders\". Do not edit.\n")
  string(APPEND shaders_out "${header_note}")
  string(APPEND shaders_out "// Included by render_graph/shader_library.cpp inside namespace premation::rg.\n\n")
  set(table_rows "")
  set(listed "")
  foreach(i RANGE ${last_shader})
    string(JSON name GET "${shader_list}" ${i})
    if(NOT name MATCHES "^[a-z0-9][a-z0-9._-]*$")
      message(FATAL_ERROR "embed_wgsl: shader name \"${name}\" is not a plain file name")
    endif()
    if("${name}" IN_LIST listed)
      message(FATAL_ERROR "embed_wgsl: shader \"${name}\" is listed twice")
    endif()
    list(APPEND listed "${name}")
    set(src "${_PREMATION_WGSL_DIR}/wgsl/${name}.wgsl")
    if(NOT EXISTS "${src}")
      message(FATAL_ERROR "embed_wgsl: materials.json lists \"${name}\" but ${src} does not exist")
    endif()
    _premation_configure_depends("${src}")
    file(READ "${src}" wgsl)
    # A Windows checkout with core.autocrlf must not change the shader bytes.
    string(REPLACE "\r" "" wgsl "${wgsl}")
    set(wgsl_${i} "${wgsl}")
    _premation_raw_pieces("${wgsl}" "${name}" pieces n_pieces)
    string(APPEND shaders_out "// ${name}\ninline constexpr const char* kWgsl${i}[] = {\n  ${pieces},\n};\n")
    string(APPEND table_rows "  {\"${name}\", kWgsl${i}, ${n_pieces}},\n")
  endforeach()
  string(APPEND shaders_out "\ninline constexpr BuiltinShader kBuiltinShaders[] = {\n${table_rows}};\n")

  # A shader file nobody lists is a forgotten table entry, not dead weight.
  file(GLOB on_disk RELATIVE "${_PREMATION_WGSL_DIR}/wgsl" "${_PREMATION_WGSL_DIR}/wgsl/*.wgsl")
  foreach(f IN LISTS on_disk)
    string(REGEX REPLACE "\\.wgsl$" "" stem "${f}")
    if(NOT "${stem}" IN_LIST listed)
      message(FATAL_ERROR "embed_wgsl: wgsl/${f} is not listed in materials.json \"shaders\"")
    endif()
  endforeach()

  # ── renderer_wgsl.hpp (C1 prototype picks) ──────────────────────────────
  set(pick_out "// GENERATED from native/engine/shaders/wgsl/*.wgsl. Do not edit.\n")
  string(APPEND pick_out "${header_note}#pragma once\n\nnamespace premation::shaders {\n")
  set(pick ${_PREMATION_WGSL_PICK})
  while(pick)
    list(POP_FRONT pick name ident)
    list(FIND listed "${name}" idx)
    if(idx EQUAL -1)
      message(FATAL_ERROR "embed_wgsl: no shader named ${name} in materials.json")
    endif()
    string(FIND "${wgsl_${idx}}" ")WGSL\"" clash)
    if(NOT clash EQUAL -1)
      message(FATAL_ERROR "embed_wgsl: ${name}: delimiter clash")
    endif()
    string(APPEND pick_out "\n// ${name}\ninline constexpr const char* ${ident} = R\"WGSL(${wgsl_${idx}})WGSL\";\n")
  endwhile()
  string(APPEND pick_out "\n}  // namespace premation::shaders\n")

  # ── materials.inc ────────────────────────────────────────────────────────
  string(JSON n_mats LENGTH "${mat_list}")
  math(EXPR last_mat "${n_mats} - 1")
  set(mat_out "// GENERATED from native/engine/shaders/materials.json \"materials\". Do not edit.\n")
  string(APPEND mat_out "${header_note}")
  string(APPEND mat_out "// Included by render_graph/materials.hpp inside namespace premation::rg.\n\n")
  set(enum_rows "")
  set(decls "")
  set(rows "")
  foreach(m RANGE ${last_mat})
    string(JSON mat GET "${mat_list}" ${m})
    string(JSON name GET "${mat}" name)
    string(JSON shader GET "${mat}" shader)
    if(NOT name MATCHES "^[A-Z][A-Z0-9_]*$")
      message(FATAL_ERROR "embed_wgsl: material name \"${name}\" is not a C++ identifier")
    endif()
    if(NOT "${shader}" IN_LIST listed)
      message(FATAL_ERROR "embed_wgsl: ${name}: shader \"${shader}\" is not in materials.json \"shaders\"")
    endif()
    string(APPEND enum_rows "  ${name},\n")

    string(JSON n_entries LENGTH "${mat}" layout)
    set(entries "")
    if(n_entries GREATER 0)
      math(EXPR last_entry "${n_entries} - 1")
      foreach(e RANGE ${last_entry})
        string(JSON binding GET "${mat}" layout ${e} binding)
        string(JSON type GET "${mat}" layout ${e} type)
        if(type STREQUAL "uniform-buffer")
          set(type uniform)
        elseif(type STREQUAL "storage-buffer")
          set(type storage)
        elseif(type STREQUAL "texture" OR type STREQUAL "sampler")
        elseif(type STREQUAL "depth-texture")
          set(type depth)
        else()
          message(FATAL_ERROR "embed_wgsl: ${name}: unknown binding type \"${type}\"")
        endif()
        string(JSON n_stages LENGTH "${mat}" layout ${e} stages)
        math(EXPR last_stage "${n_stages} - 1")
        set(stages "")
        foreach(s RANGE ${last_stage})
          string(JSON stage GET "${mat}" layout ${e} stages ${s})
          if(stage STREQUAL "vertex")
            set(stage kStageVertex)
          elseif(stage STREQUAL "fragment")
            set(stage kStageFragment)
          else()
            set(stage kStageCompute)
          endif()
          if(s GREATER 0)
            string(APPEND stages " | ")
          endif()
          string(APPEND stages "${stage}")
        endforeach()
        if(e GREATER 0)
          string(APPEND entries ", ")
        endif()
        string(APPEND entries "{${binding}, BindingType::${type}, ${stages}}")
      endforeach()
    endif()
    string(APPEND decls "inline constexpr LayoutEntry kLayout_${name}[] = {${entries}};\n")

    string(JSON buffers_type ERROR_VARIABLE no_buffers TYPE "${mat}" buffers)
    if(no_buffers)
      set(bufs_ref "std::span<const VertexLayout>{}")
    else()
      string(JSON n_bufs LENGTH "${mat}" buffers)
      math(EXPR last_buf "${n_bufs} - 1")
      set(bufs "")
      foreach(b RANGE ${last_buf})
        string(JSON n_attrs LENGTH "${mat}" buffers ${b} attributes)
        math(EXPR last_attr "${n_attrs} - 1")
        set(attrs "")
        foreach(a RANGE ${last_attr})
          string(JSON loc GET "${mat}" buffers ${b} attributes ${a} shaderLocation)
          string(JSON off GET "${mat}" buffers ${b} attributes ${a} offsetBytes)
          string(JSON fmt GET "${mat}" buffers ${b} attributes ${a} format)
          if(fmt STREQUAL "float32")
            set(fmt Float32)
          elseif(fmt MATCHES "^float32x([234])$")
            set(fmt "Float32x${CMAKE_MATCH_1}")
          else()
            message(FATAL_ERROR "embed_wgsl: ${name}: unknown vertex format \"${fmt}\"")
          endif()
          if(a GREATER 0)
            string(APPEND attrs ", ")
          endif()
          string(APPEND attrs "{${loc}, ${off}, VertexFormat::${fmt}}")
        endforeach()
        string(APPEND decls "inline constexpr VertexAttr kAttrs_${name}_${b}[] = {${attrs}};\n")
        string(JSON stride GET "${mat}" buffers ${b} strideBytes)
        string(JSON step GET "${mat}" buffers ${b} stepMode)
        if(step STREQUAL "instance")
          set(instance true)
        else()
          set(instance false)
        endif()
        if(b GREATER 0)
          string(APPEND bufs ", ")
        endif()
        string(APPEND bufs "{${stride}, ${instance}, kAttrs_${name}_${b}}")
      endforeach()
      string(APPEND decls "inline constexpr VertexLayout kBuffers_${name}[] = {${bufs}};\n")
      set(bufs_ref "kBuffers_${name}")
    endif()

    string(JSON depth_type ERROR_VARIABLE no_depth TYPE "${mat}" depth)
    if(no_depth)
      set(depth "false, false, false")
    else()
      string(JSON d_test GET "${mat}" depth test)
      string(JSON d_write GET "${mat}" depth write)
      # string(JSON GET) answers booleans as ON / OFF.
      set(depth "true")
      foreach(flag d_test d_write)
        if(${flag})
          string(APPEND depth ", true")
        else()
          string(APPEND depth ", false")
        endif()
      endforeach()
    endif()
    string(APPEND rows "  {\"${name}\", \"${shader}\", kLayout_${name}, ${bufs_ref}, ${depth}},\n")
  endforeach()
  string(APPEND mat_out "enum class Mat : std::uint16_t {\n${enum_rows}  Count_\n};\n\n${decls}")
  string(APPEND mat_out "\ninline constexpr MaterialDesc kMaterials[] = {\n${rows}};\n")
  string(APPEND mat_out "static_assert(std::size(kMaterials) == static_cast<std::size_t>(Mat::Count_));\n")

  file(MAKE_DIRECTORY "${out_dir}")
  _premation_write_if_changed("${out_dir}/builtin_shaders.inc" "${shaders_out}")
  _premation_write_if_changed("${out_dir}/materials.inc" "${mat_out}")
  _premation_write_if_changed("${out_dir}/renderer_wgsl.hpp" "${pick_out}")
endfunction()

# `cmake -DOUT=<dir> -P embed_wgsl.cmake` runs the generator on its own (for
# comparing its output with a previous build's).
if(CMAKE_SCRIPT_MODE_FILE STREQUAL CMAKE_CURRENT_LIST_FILE)
  if(NOT DEFINED OUT)
    message(FATAL_ERROR "usage: cmake -DOUT=<dir> -P embed_wgsl.cmake")
  endif()
  premation_embed_wgsl("${OUT}")
endif()
