#!/usr/bin/env node
/**
 * Pull WGSL out of packages/renderer VERBATIM — the exact strings the
 * TypeScript engine hands to WebGPU (template literals resolved, the
 * `unpremultiplyingSample` rewrites applied) — and the material table that
 * binds them to pipeline state, and write them as C++ the engine compiles in.
 *
 *   node native/engine/shaders/extract.mjs          regenerate
 *   node native/engine/shaders/extract.mjs --check  exit 1 if any output is stale
 *
 * Outputs (committed, so the C++ build never needs Node):
 *   renderer_wgsl.hpp      C1's hand-picked three (textured, blur, vignette),
 *                          kept for the viewport prototype
 *   builtin_shaders.inc    D2: EVERY entry of BUILTIN_SHADERS, by name
 *   materials.inc          D2: every exported `*_MATERIAL` descriptor of
 *                          shaders/Material.ts (shader, bind-group layout, vertex
 *                          buffers, depth state), as constexpr data
 *
 * --check is the drift detector: a TS shader or material edit that is not
 * re-extracted fails it, so the C++ render graph can never silently run older
 * WGSL than the TypeScript engine it is compared against.
 */

import { build } from 'esbuild';
import { readFileSync, writeFileSync, mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '..', '..', '..');
const shadersDir = join(root, 'packages', 'renderer', 'src', 'shaders');

// name in BUILTIN_SHADERS → C++ identifier (the C1 prototype's header)
const PICK = [
  ['textured', 'kTexturedWgsl'],
  ['blur', 'kBlurWgsl'],
  ['vignette', 'kVignetteWgsl'],
];

/** Raw-string pieces stay under the 65,536 characters -Wpedantic lets a literal have. */
const CHUNK = 30000;

function rawPieces(text, label) {
  if (text.includes(')WGSL"')) throw new Error(`${label}: delimiter clash`);
  const parts = [];
  for (let i = 0; i < text.length; i += CHUNK) parts.push(`R"WGSL(${text.slice(i, i + CHUNK)})WGSL"`);
  return parts.length ? parts : ['""'];
}

const FORMAT = { float32x2: 'Float32x2', float32x3: 'Float32x3', float32x4: 'Float32x4', float32: 'Float32' };
const BINDING = { 'uniform-buffer': 'uniform', 'storage-buffer': 'storage', texture: 'texture', sampler: 'sampler', 'depth-texture': 'depth' };

function genShaders(list) {
  let out = '// GENERATED by native/engine/shaders/extract.mjs from\n';
  out += '// packages/renderer/src/shaders/builtin.ts (BUILTIN_SHADERS). Do not edit.\n';
  out += '// Regenerate: node native/engine/shaders/extract.mjs\n';
  out += '// Included by render_graph/shader_library.cpp inside namespace premation::rg.\n\n';
  const names = [];
  list.forEach((s, i) => {
    const pieces = rawPieces(s.wgsl, s.name);
    out += `// ${s.name}\ninline constexpr const char* kWgsl${i}[] = {\n  ${pieces.join(',\n  ')},\n};\n`;
    names.push([s.name, i, pieces.length]);
  });
  out += '\ninline constexpr BuiltinShader kBuiltinShaders[] = {\n';
  for (const [name, i, n] of names) out += `  {"${name}", kWgsl${i}, ${n}},\n`;
  out += '};\n';
  return out;
}

function genMaterials(mats) {
  let out = '// GENERATED by native/engine/shaders/extract.mjs from\n';
  out += '// packages/renderer/src/shaders/Material.ts (every exported *_MATERIAL). Do not edit.\n';
  out += '// Regenerate: node native/engine/shaders/extract.mjs\n';
  out += '// Included by render_graph/materials.hpp inside namespace premation::rg.\n\n';
  out += 'enum class Mat : std::uint16_t {\n';
  for (const [name] of mats) out += `  ${name},\n`;
  out += '  Count_\n};\n\n';
  mats.forEach(([name, m]) => {
    const entries = m.layout.map((e) => {
      const stages = e.stages.map((s) => (s === 'vertex' ? 'kStageVertex' : s === 'fragment' ? 'kStageFragment' : 'kStageCompute')).join(' | ');
      return `{${e.binding}, BindingType::${BINDING[e.type]}, ${stages}}`;
    });
    out += `inline constexpr LayoutEntry kLayout_${name}[] = {${entries.join(', ')}};\n`;
    if (m.buffers) {
      m.buffers.forEach((b, bi) => {
        const attrs = b.attributes.map((a) => `{${a.shaderLocation}, ${a.offsetBytes}, VertexFormat::${FORMAT[a.format]}}`);
        out += `inline constexpr VertexAttr kAttrs_${name}_${bi}[] = {${attrs.join(', ')}};\n`;
      });
      const bufs = m.buffers.map((b, bi) => `{${b.strideBytes}, ${b.stepMode === 'instance' ? 'true' : 'false'}, kAttrs_${name}_${bi}}`);
      out += `inline constexpr VertexLayout kBuffers_${name}[] = {${bufs.join(', ')}};\n`;
    }
  });
  out += '\ninline constexpr MaterialDesc kMaterials[] = {\n';
  for (const [name, m] of mats) {
    const d = m.depth ? `true, ${m.depth.test}, ${m.depth.write}` : 'false, false, false';
    const bufs = m.buffers ? `kBuffers_${name}` : 'std::span<const VertexLayout>{}';
    out += `  {"${name}", "${m.shader}", kLayout_${name}, ${bufs}, ${d}},\n`;
  }
  out += '};\n';
  out += `static_assert(std::size(kMaterials) == static_cast<std::size_t>(Mat::Count_));\n`;
  return out;
}

function genPick(list) {
  let out = '// GENERATED by native/engine/shaders/extract.mjs from\n';
  out += '// packages/renderer/src/shaders/builtin.ts (BUILTIN_SHADERS). Do not edit.\n';
  out += '// Regenerate: node native/engine/shaders/extract.mjs\n#pragma once\n\nnamespace premation::shaders {\n';
  for (const [name, ident] of PICK) {
    const src = list.find((s) => s.name === name);
    if (!src) throw new Error(`no shader named ${name} in BUILTIN_SHADERS`);
    if (src.wgsl.includes(')WGSL"')) throw new Error(`${name}: delimiter clash`);
    out += `\n// ${name}\ninline constexpr const char* ${ident} = R"WGSL(${src.wgsl})WGSL";\n`;
  }
  out += '\n}  // namespace premation::shaders\n';
  return out;
}

const tmp = mkdtempSync(join(tmpdir(), 'premation-wgsl-'));
try {
  const bundle = join(tmp, 'renderer-shaders.mjs');
  await build({
    stdin: {
      contents: "export { BUILTIN_SHADERS } from './builtin.ts'; export * as MATERIALS from './Material.ts';",
      resolveDir: shadersDir,
      loader: 'ts',
    },
    bundle: true, format: 'esm', platform: 'node', outfile: bundle, logLevel: 'error',
  });
  const { BUILTIN_SHADERS, MATERIALS } = await import(pathToFileURL(bundle).href);
  const mats = Object.entries(MATERIALS)
    .filter(([k, v]) => k.endsWith('_MATERIAL') && v && typeof v === 'object' && typeof v.shader === 'string')
    .sort((a, b) => a[0].localeCompare(b[0]));
  for (const [name, m] of mats) {
    if (!BUILTIN_SHADERS.some((s) => s.name === m.shader)) throw new Error(`${name}: shader "${m.shader}" is not in BUILTIN_SHADERS`);
    if (m.topology !== 'triangle-list') throw new Error(`${name}: topology ${m.topology} is not supported by the C++ table`);
  }

  const outputs = [
    [join(here, 'renderer_wgsl.hpp'), genPick(BUILTIN_SHADERS)],
    [join(here, 'builtin_shaders.inc'), genShaders(BUILTIN_SHADERS)],
    [join(here, 'materials.inc'), genMaterials(mats)],
  ];

  if (process.argv.includes('--check')) {
    const stale = outputs.filter(([file, text]) => {
      try { return readFileSync(file, 'utf8') !== text; } catch { return true; }
    });
    if (stale.length) {
      console.error(`stale — run node native/engine/shaders/extract.mjs:\n  ${stale.map(([f]) => f).join('\n  ')}`);
      process.exit(1);
    }
    console.log(`shaders up to date (${BUILTIN_SHADERS.length} shaders, ${mats.length} materials)`);
  } else {
    for (const [file, text] of outputs) writeFileSync(file, text);
    console.log(`wrote ${outputs.length} files (${BUILTIN_SHADERS.length} shaders, ${mats.length} materials)`);
  }
} finally {
  rmSync(tmp, { recursive: true, force: true });
}
