#!/usr/bin/env node
/**
 * Pull WGSL out of packages/renderer VERBATIM — the exact strings the
 * TypeScript engine hands to WebGPU (template literals resolved, the
 * `unpremultiplyingSample` rewrites applied) — and write them to
 * native/engine/shaders/renderer_wgsl.hpp as raw string literals.
 *
 *   node native/engine/shaders/extract.mjs          regenerate
 *   node native/engine/shaders/extract.mjs --check  exit 1 if the header is stale
 *
 * The header is committed so the C++ build never needs Node. This is the C1
 * proof that the engine reuses our WGSL unmodified; D2 replaces the hand-picked
 * list with the whole BUILTIN_SHADERS table.
 */

import { build } from 'esbuild';
import { readFileSync, writeFileSync, mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '..', '..', '..');
const entry = join(root, 'packages', 'renderer', 'src', 'shaders', 'builtin.ts');
const outFile = join(here, 'renderer_wgsl.hpp');

// name in BUILTIN_SHADERS → C++ identifier
const PICK = [
  ['textured', 'kTexturedWgsl'],
  ['blur', 'kBlurWgsl'],
  ['vignette', 'kVignetteWgsl'],
];

const tmp = mkdtempSync(join(tmpdir(), 'premation-wgsl-'));
try {
  const bundle = join(tmp, 'builtin.mjs');
  await build({ entryPoints: [entry], bundle: true, format: 'esm', platform: 'node', outfile: bundle, logLevel: 'error' });
  const { BUILTIN_SHADERS } = await import(pathToFileURL(bundle).href);

  let out = '// GENERATED by native/engine/shaders/extract.mjs from\n';
  out += '// packages/renderer/src/shaders/builtin.ts (BUILTIN_SHADERS). Do not edit.\n';
  out += '// Regenerate: node native/engine/shaders/extract.mjs\n#pragma once\n\nnamespace premation::shaders {\n';
  for (const [name, ident] of PICK) {
    const src = BUILTIN_SHADERS.find((s) => s.name === name);
    if (!src) throw new Error(`no shader named ${name} in BUILTIN_SHADERS`);
    if (src.wgsl.includes(')WGSL"')) throw new Error(`${name}: delimiter clash`);
    out += `\n// ${name}\ninline constexpr const char* ${ident} = R"WGSL(${src.wgsl})WGSL";\n`;
  }
  out += '\n}  // namespace premation::shaders\n';

  if (process.argv.includes('--check')) {
    let cur = '';
    try { cur = readFileSync(outFile, 'utf8'); } catch { /* missing = stale */ }
    if (cur !== out) {
      console.error(`${outFile} is stale — run node native/engine/shaders/extract.mjs`);
      process.exit(1);
    }
    console.log('renderer_wgsl.hpp is up to date');
  } else {
    writeFileSync(outFile, out);
    console.log(`wrote ${outFile} (${PICK.map((p) => p[0]).join(', ')})`);
  }
} finally {
  rmSync(tmp, { recursive: true, force: true });
}
