#!/usr/bin/env node
/**
 * Generate the raster module's Unicode tables FROM THE TYPESCRIPT, so the C++
 * text layout reads exactly the data the TS layout reads:
 *
 *   vertical_orientation.inc   src/core/text/verticalOrientationData.ts (UAX #50)
 *
 *   node native/engine/src/raster/gen_tables.mjs [--check]
 */
import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, '..', '..', '..', '..');
const check = process.argv.includes('--check');

const src = readFileSync(path.join(root, 'src/core/text/verticalOrientationData.ts'), 'utf8');
const starts = /VO_RANGE_STARTS[^=]*=\s*\[([\s\S]*?)\];/.exec(src)[1].split(',').map((s) => s.trim()).filter(Boolean);
const values = [...(/VO_RANGE_VALUES\s*=([\s\S]*?);/.exec(src)[1].matchAll(/'([^']*)'/g))].map((m) => m[1]).join('');
if (starts.length !== values.length) throw new Error(`starts ${starts.length} != values ${values.length}`);
const version = /VERTICAL_ORIENTATION_UNICODE_VERSION = '([^']+)'/.exec(src)[1];

let out = '// GENERATED by native/engine/src/raster/gen_tables.mjs from src/core/text/verticalOrientationData.ts — do not edit.\n';
out += `// Unicode ${version} Vertical_Orientation: range starts + values (U, R, u = Tu, r = Tr).\n`;
out += `inline constexpr std::array<char32_t, ${starts.length}> kVoStarts{{\n`;
for (let i = 0; i < starts.length; i += 12) out += `  ${starts.slice(i, i + 12).join(', ')},\n`;
out += '}};\n';
out += `inline constexpr std::string_view kVoValues =\n`;
for (let i = 0; i < values.length; i += 96) out += `  "${values.slice(i, i + 96)}"\n`;
out += ';\n';

// lineBreak.ts kinsoku sets (JIS X 4051): the TS builds each Set from string literals.
const lb = readFileSync(path.join(root, 'src/core/text/lineBreak.ts'), 'utf8');
const setCodePoints = (name) => {
  const body = new RegExp(`${name}[^=]*=\\s*new Set\\(cps\\(([\\s\\S]*?)\\)\\);`).exec(lb)[1];
  const text = [...body.matchAll(/'((?:[^'\\]|\\.)*)'/g)].map((m) => m[1]).join('');
  return [...text].map((c) => c.codePointAt(0));
};
const hexList = (cps) => cps.map((c) => `0x${c.toString(16)}`).join(', ');
const noStart = setCodePoints('KINSOKU_NO_LINE_START');
const noEnd = setCodePoints('KINSOKU_NO_LINE_END');
out += `// lineBreak.ts KINSOKU_NO_LINE_START / KINSOKU_NO_LINE_END (JIS X 4051).\n`;
out += `inline constexpr std::array<char32_t, ${noStart.length}> kKinsokuNoStart{{${hexList(noStart)}}};\n`;
out += `inline constexpr std::array<char32_t, ${noEnd.length}> kKinsokuNoEnd{{${hexList(noEnd)}}};\n`;

// verticalForms.ts VERTICAL_PRESENTATION_FORMS + CORNER_PUNCTUATION.
const vf = readFileSync(path.join(root, 'src/core/text/verticalForms.ts'), 'utf8');
const pairs = [...(/VERTICAL_PRESENTATION_FORMS[^=]*=\s*new Map\(\[([\s\S]*?)\]\);/.exec(vf)[1].matchAll(/\[(0x[0-9a-f]+),\s*(0x[0-9a-f]+)\]/gi))]
  .map((m) => `{${m[1]}, ${m[2]}}`);
const corner = /CORNER_PUNCTUATION[^=]*=\s*new Set\(\[([^\]]*)\]\)/.exec(vf)[1].split(',').map((s) => s.trim()).filter(Boolean);
out += `// verticalForms.ts VERTICAL_PRESENTATION_FORMS (horizontal → vertical presentation form) and CORNER_PUNCTUATION.\n`;
out += `inline constexpr std::array<std::pair<char32_t, char32_t>, ${pairs.length}> kVerticalForms{{${pairs.join(', ')}}};\n`;
out += `inline constexpr std::array<char32_t, ${corner.length}> kCornerPunctuation{{${corner.join(', ')}}};\n`;

const file = path.join(here, 'vertical_orientation.inc');
const text = out.replace(/\n/g, '\r\n');
if (check) {
  const cur = readFileSync(file, 'utf8');
  if (cur !== text) {
    console.error('vertical_orientation.inc is stale — run node native/engine/src/raster/gen_tables.mjs');
    process.exit(1);
  }
  console.log('raster tables up to date');
} else {
  writeFileSync(file, text);
  console.log(`wrote ${path.relative(root, file)} (${starts.length} ranges)`);
}
