/**
 * Cross-engine parity of the CANVAS-DRAWN effects (plan E4 × E3):
 * `native/engine/src/effects/canvas_effects.cpp` ports fill, linear-wipe,
 * checkerboard, grid, circle, ellipse, radio-waves, light-rays and light-sweep
 * call for call onto the C++ Canvas2D. This test runs the TS
 * `applyCanvas2dEffect` for each on a recording canvas and stores the Canvas2D
 * program, with the effect's resolved params (`paramsOf`), in
 * `native/engine/tests/data/canvas_effects_parity.json`;
 * `native/engine/tests/test_canvas_effects.cpp` requires the C++ to issue the
 * same program op for op.
 *
 * `GEN_NATIVE_CANVAS_EFFECTS=1 npx jest canvasEffectsCrossEngine` rewrites the
 * fixture; without it this test fails when the fixture is stale.
 */

import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { applyCanvas2dEffect } from './canvas2dEffects';
import { paramsOf, type Effect } from './effects';
import { beginRecording, recordingCanvas, withRecordingCanvases } from '@core/rendering/raster/__testHelpers__/recordingCanvas';

const OUT = path.resolve(__dirname, '../../../native/engine/tests/data/canvas_effects_parity.json');

const E = (type: string, params: Record<string, number | string | boolean>): Effect =>
  ({ id: `fx-${type}`, type, enabled: true, params } as unknown as Effect);

const CASES: Array<{ effect: Effect; w: number; h: number }> = [
  { effect: E('fill', { color: '#ff8800', opacity: 60 }), w: 96, h: 64 },
  { effect: E('fill', { color: '#ff8800', opacity: 0 }), w: 96, h: 64 },
  { effect: E('linear-wipe', { completion: 40, wipeAngle: 30, feather: 12 }), w: 120, h: 80 },
  { effect: E('linear-wipe', { completion: 100 }), w: 120, h: 80 },
  { effect: E('linear-wipe', { completion: 55.5, wipeAngle: -110, feather: 0 }), w: 120, h: 80 },
  { effect: E('checkerboard', { width: 17, height: 13, anchorX: -5.5, anchorY: 30, colorA: '#102030', colorB: '#f0e0d0', opacity: 70 }), w: 100, h: 60 },
  { effect: E('checkerboard', { width: 0.2, height: 25, opacity: 150 }), w: 40, h: 50 },
  { effect: E('grid', { width: 20, height: 15, thickness: 1, anchorX: 3, anchorY: 4, opacity: 90, color: '#00ff88' }), w: 100, h: 70 },
  { effect: E('grid', { width: 12.5, height: 30, thickness: 2.6, anchorX: -7, opacity: 40 }), w: 90, h: 64 },
  { effect: E('circle', { radius: 30, feather: 10, centerX: 5, centerY: -3, opacity: 80, composite: 1, color: '#3355ff' }), w: 120, h: 100 },
  { effect: E('circle', { radius: 36, feather: 3, thickness: 8, opacity: 100, color: '#fa0' }), w: 120, h: 100 },
  { effect: E('circle', { radius: 25, feather: 0, invertCircle: true, opacity: 50, color: 'red' }), w: 120, h: 100 },
  { effect: E('circle', { radius: 25, feather: 40, thickness: 30, opacity: 90 }), w: 120, h: 100 },
  { effect: E('ellipse', { ellipseWidth: 80, ellipseHeight: 40, rotation: 25, thickness: 3, softness: 6, composite: 2, opacity: 90, color: '#ff0080' }), w: 140, h: 100 },
  { effect: E('ellipse', { ellipseWidth: 50, ellipseHeight: 70, rotation: -10, thickness: 0.2, softness: 0, centerX: 12 }), w: 140, h: 100 },
  { effect: E('radio-waves', { waveCount: 5, maxRadius: 0, phase: 100, thickness: 2, fadeOut: 60, opacity: 90 }), w: 150, h: 110 },
  { effect: E('radio-waves', { waveCount: 7.6, maxRadius: 50, phase: -45, thickness: 4, fadeOut: 100, composite: 4, color: '#abc' }), w: 150, h: 110 },
  { effect: E('light-rays', { rayCount: 12, rayLength: 80, spread: 50, rotation: 10, falloff: 40, seed: 3, composite: 1, opacity: 85 }), w: 160, h: 120 },
  { effect: E('light-rays', { rayCount: 40, rayLength: 120, spread: 0, seed: 123456, falloff: 90, opacity: 70, centerX: -20 }), w: 160, h: 120 },
  { effect: E('light-sweep', { position: 30, sweepWidth: 40, angle: 20, intensity: 80, softness: 50 }), w: 130, h: 90 },
  { effect: E('light-sweep', { position: 150, sweepWidth: 25, angle: 95, intensity: 100, softness: 0, composite: 1 }), w: 130, h: 90 },
];

function generate() {
  return CASES.map(({ effect, w, h }) => {
    const ops = beginRecording();
    const { ctx } = recordingCanvas(w, h);
    // Prelude: some content for the source-atop / destination-out effects to act on.
    ctx.fillStyle = '#3366cc';
    ctx.fillRect(w / 4, h / 4, w / 2, h / 2);
    withRecordingCanvases(() => applyCanvas2dEffect(ctx as unknown as CanvasRenderingContext2D, w, h, effect));
    return { type: effect.type, w, h, params: paramsOf(effect), ops: ops.map((op) => JSON.stringify(op)) };
  });
}

test('the C++ canvas-effect parity fixture matches canvas2dEffects.ts', () => {
  const cases = generate();
  const text = `${JSON.stringify({ comment: 'Generated by src/core/effects/canvasEffectsCrossEngine.test.ts (GEN_NATIVE_CANVAS_EFFECTS=1). Do not edit.', cases }, null, 1)}\n`;
  if (process.env.GEN_NATIVE_CANVAS_EFFECTS === '1') {
    writeFileSync(OUT, text);
    return;
  }
  expect(existsSync(OUT)).toBe(true);
  expect(JSON.parse(readFileSync(OUT, 'utf8'))).toEqual(JSON.parse(text));
});
