/**
 * Cross-engine parity of `styledSurfaceFill` (layerStyles.ts) — the wall colour
 * of an extrusion under a Colour / Gradient Overlay style (plan D2w 3D
 * leftovers). The C++ port (`native/engine/src/scene/styled_surface.cpp`,
 * tests/test_styled_surface_parity.cpp) must give the same `#rrggbb` string.
 *
 * `GEN_NATIVE_STYLED=1 npx jest styledSurfaceCrossEngine` rewrites the fixture.
 */

import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { styledSurfaceFill, type LayerStyles } from './layerStyles';

const OUT = path.resolve(__dirname, '../../../native/engine/tests/data/styled_surface_parity.json');

const BASES = ['#2a2a2a', '#c9a05a', '#fff', '#12345678', 'rgba(10, 200, 30, 0.5)', 'not-a-colour'];
const STYLES: Array<Record<string, unknown> | undefined> = [
  undefined,
  {},
  { colorOverlay: { enabled: true, color: '#ff2d55', opacity: 1 } },
  { colorOverlay: { enabled: true, color: '#ff2d55', opacity: 0.35 } },
  { colorOverlay: { enabled: false, color: '#ff2d55', opacity: 1 } },
  { colorOverlay: { enabled: true, color: '#00f', opacity: 0 } },
  { colorOverlay: { enabled: true, color: '#00ff00', opacity: 1.7 } },
  { gradientOverlay: { enabled: true, from: '#ffffff', to: '#2b7eff', opacity: 1, angle: 90 } },
  { gradientOverlay: { enabled: true, from: '#101010', to: '#fe0', opacity: 0.6, angle: 0 } },
  {
    colorOverlay: { enabled: true, color: '#336699', opacity: 0.5 },
    gradientOverlay: { enabled: true, from: '#ff0000', to: '#0000ff', opacity: 0.25, angle: 45 },
  },
];

function generate() {
  const rows: { base: string; styles: unknown; fill: string }[] = [];
  for (const base of BASES) {
    for (const s of STYLES) rows.push({ base, styles: s ?? null, fill: styledSurfaceFill(s as LayerStyles | undefined, base) });
  }
  return rows;
}

test('the C++ styled surface fill fixture matches styledSurfaceFill', () => {
  const rows = generate();
  const text = `${JSON.stringify({ comment: 'Generated by src/core/effects/styledSurfaceCrossEngine.test.ts (GEN_NATIVE_STYLED=1). Do not edit.', rows })}\n`;
  if (process.env.GEN_NATIVE_STYLED === '1') {
    writeFileSync(OUT, text);
    return;
  }
  expect(existsSync(OUT)).toBe(true);
  expect((JSON.parse(readFileSync(OUT, 'utf8')) as { rows: unknown[] }).rows).toEqual(rows);
});
