/**
 * Cross-engine parity of Write-on's brush form hand-off (plan D2w effects):
 * `resolveWriteOnTrail` — the dab history buildSnapshot samples at past times.
 *
 * Each case fixes the effect params, the layer time, the node's first key and
 * which tracks are animated; the sampler is a closed-form function of (prop, t)
 * and every call it answers is recorded, so the C++ port
 * (`native/engine/src/scene/write_on_trail.cpp`,
 * tests/test_write_on_trail_parity.cpp) replays the SAME answers and must ask at
 * the same times and produce the same trail, float for float.
 *
 * `GEN_NATIVE_WRITEON=1 npx jest writeOnTrailCrossEngine` rewrites the fixture.
 */

import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import type { EffectParams } from './effects';
import { resolveWriteOnTrail } from './writeOnBrush';

const OUT = path.resolve(__dirname, '../../../native/engine/tests/data/write_on_trail_parity.json');

interface Case {
  name: string;
  params: EffectParams;
  t: number;
  earliest?: number;
  animated: string[];
  /** Props whose sampler answers undefined (a track that yields nothing). */
  silent?: string[];
}

const BASE: EffectParams = {
  writeOnMode: 0, brushPositionX: 12, brushPositionY: -4, brushColor: '#33aaff', brushSize: 10,
  brushHardness: 60, brushOpacity: 90, strokeLength: 0, brushSpacing: 0.05,
};

const CASES: Case[] = [
  { name: 'static brush is one dab', params: BASE, t: 1.2, earliest: 0, animated: [] },
  { name: 'position only, from the first key', params: BASE, t: 1, earliest: 0.25, animated: ['brushPositionX', 'brushPositionY'] },
  { name: 'x only', params: BASE, t: 0.5, earliest: 0, animated: ['brushPositionX'] },
  { name: 'no first key → one dab at the playhead', params: BASE, t: 0.7, animated: ['brushPositionY'] },
  { name: 'stroke length snake', params: { ...BASE, strokeLength: 0.3 }, t: 2.013, earliest: 0, animated: ['brushPositionX', 'brushPositionY', 'brushSize'] },
  { name: 'every track, time-varying colour', params: BASE, t: 0.83, earliest: 0.1,
    animated: ['brushPositionX', 'brushPositionY', 'brushSize', 'brushHardness', 'brushOpacity', 'brushColor_r', 'brushColor_g', 'brushColor_b'] },
  { name: 'colour track out of range clamps', params: { ...BASE, brushColor: 'zz' }, t: 0.4, earliest: 0, animated: ['brushPositionX', 'brushColor_g'] },
  { name: 'silent tracks fall back', params: BASE, t: 0.6, earliest: 0, animated: ['brushPositionX', 'brushSize', 'brushColor_b'], silent: ['brushSize', 'brushColor_b'] },
  { name: 'playhead on the grid', params: { ...BASE, brushSpacing: 0.25 }, t: 1.5, earliest: 0, animated: ['brushPositionX'] },
  { name: 'AE default spacing, thinned', params: { ...BASE, brushSpacing: 0.001 }, t: 3.3, earliest: 0, animated: ['brushPositionX', 'brushPositionY'] },
  { name: 'spacing below the floor', params: { ...BASE, brushSpacing: 0.0001 }, t: 0.05, earliest: 0, animated: ['brushPositionX'] },
  { name: 'first key after the playhead', params: BASE, t: 0.2, earliest: 0.9, animated: ['brushPositionX'] },
  { name: 'non-finite / missing params use defaults', params: { writeOnMode: 0, brushSpacing: Number.NaN, brushColor: ' #ABCDEF99 ' }, t: 0.31, earliest: 0, animated: ['brushPositionY'] },
];

/** A deterministic answer per (prop, t): a few sines, exact in both engines only because it is RECORDED. */
function answer(prop: string, t: number): number {
  let h = 0;
  for (let i = 0; i < prop.length; i++) h = (h * 31 + prop.charCodeAt(i)) % 997;
  if (prop.endsWith('_r') || prop.endsWith('_g') || prop.endsWith('_b')) return 0.5 + 0.8 * Math.sin(t * 5 + h);
  return 100 * Math.sin(t * 2.3 + h) + 7 * t;
}

function generate() {
  return CASES.map((c) => {
    const id = 'fx1';
    const animated = new Set(c.animated.map((k) => `effect.${id}.${k}`));
    const silent = new Set((c.silent ?? []).map((k) => `effect.${id}.${k}`));
    const samples: Array<[string, number, number | null]> = [];
    const trail = resolveWriteOnTrail(
      id, c.params, c.t,
      (prop, t) => {
        const v = silent.has(prop) ? undefined : answer(prop, t);
        samples.push([prop, t, v ?? null]);
        return v;
      },
      (prop) => animated.has(prop),
      c.earliest,
    );
    return {
      name: c.name, id, params: c.params, t: c.t, earliest: c.earliest ?? null, animated: [...animated], samples,
      trail: { xy: trail.xy, size: trail.size, attr: trail.attr, filled: trail.filled },
    };
  });
}

test('the C++ Write-on trail parity fixture matches resolveWriteOnTrail', () => {
  const rows = generate();
  // JSON has no NaN: the non-finite spacing case stores null, which reads as "not a number" in both.
  const text = `${JSON.stringify({ comment: 'Generated by src/core/effects/writeOnTrailCrossEngine.test.ts (GEN_NATIVE_WRITEON=1). Do not edit.', rows })}\n`;
  if (process.env.GEN_NATIVE_WRITEON === '1') {
    writeFileSync(OUT, text);
    return;
  }
  expect(existsSync(OUT)).toBe(true);
  expect(JSON.parse(readFileSync(OUT, 'utf8'))).toEqual(JSON.parse(text));
  expect(rows.some((r) => r.trail.filled)).toBe(true);
});
