#!/usr/bin/env node
/**
 * Engine API code generator — `npm run engine-api:gen`.
 *
 * Reads the schema (packages/engine-api/schema/*.eapi, in file-name order) and
 * writes, from that ONE source:
 *
 *   packages/engine-api/src/generated/types.ts     TypeScript types
 *   packages/engine-api/src/generated/codec.ts     TypeScript binary codec
 *   packages/engine-api/src/generated/meta.ts      reflection: versions, command table
 *   native/protocol/generated/engine_api.hpp       C++ structs + codec declarations
 *   native/protocol/generated/engine_api.cpp       C++ codec
 *   native/protocol/generated/fixtures.inc         cross-language round-trip vectors
 *   electron/generated/frameChannel.ts             the FrameChannel family, standalone (Electron main)
 *   electron/generated/engineWire.ts               a copy of src/wire.ts for it
 *
 *   node packages/engine-api/codegen/generate.cjs          write the files
 *   node packages/engine-api/codegen/generate.cjs --check  exit 1 if any is stale
 *
 * CommonJS (like scripts/featureCounts.cjs) so the Jest staleness test can
 * `require` it and compare in memory instead of re-implementing it, and so it
 * runs on CI's Node 20 with no TypeScript loader and no native tool (flatc,
 * protoc) — docs/ENGINE_API.md §9 has the measured reasons.
 *
 * The wire format is documented in docs/ENGINE_API.md §9. In short: the
 * protobuf wire encoding (varint keys `field << 3 | wireType`, zigzag signed
 * ints, little-endian fixed32/fixed64 floats, length-delimited strings /
 * messages / packed numeric lists) with a CANONICAL encoder — fields in
 * field-number order, required fields always written, absent optionals and
 * empty lists never written — so the TypeScript and C++ encoders produce the
 * same bytes for the same value. `fixtures.inc` is how that is proven.
 */

'use strict';

const { readFileSync, writeFileSync, readdirSync, mkdirSync, existsSync } = require('node:fs');
const { join, dirname, relative } = require('node:path');

const ROOT = join(__dirname, '..', '..', '..');
const SCHEMA_DIR = join(__dirname, '..', 'schema');
const TS_OUT = join(__dirname, '..', 'src', 'generated');
const CPP_OUT = join(ROOT, 'native', 'protocol', 'generated');
const ELECTRON_OUT = join(ROOT, 'electron', 'generated');

const HEADER_NOTE = 'GENERATED by packages/engine-api/codegen/generate.cjs from packages/engine-api/schema/*.eapi — do not edit; run `npm run engine-api:gen`.';

// ─────────────────────────────────────────────────────────────────────────────
// Lexer
// ─────────────────────────────────────────────────────────────────────────────

function lex(src, file) {
  const toks = [];
  let i = 0;
  let line = 1;
  let pendingDoc = [];
  const push = (type, value) => {
    toks.push({ type, value, line, file, doc: type === 'ident' || type === 'string' ? pendingDoc : [] });
    if (type !== 'ident' && type !== 'string') pendingDoc = [];
    else pendingDoc = [];
  };
  while (i < src.length) {
    const c = src[i];
    if (c === '\n') { line++; i++; continue; }
    if (c === ' ' || c === '\t' || c === '\r') { i++; continue; }
    if (c === '/' && src[i + 1] === '/') {
      const end = src.indexOf('\n', i);
      const text = src.slice(i, end === -1 ? src.length : end).replace(/\r$/, '');
      if (text.startsWith('///')) pendingDoc.push(text.slice(3).replace(/^ /, ''));
      i = end === -1 ? src.length : end;
      continue;
    }
    if (/[A-Za-z_]/.test(c)) {
      let j = i + 1;
      while (j < src.length && /[A-Za-z0-9_]/.test(src[j])) j++;
      push('ident', src.slice(i, j));
      i = j;
      continue;
    }
    if (/[0-9]/.test(c)) {
      let j = i + 1;
      while (j < src.length && /[0-9]/.test(src[j])) j++;
      push('int', Number(src.slice(i, j)));
      i = j;
      continue;
    }
    if (c === '"') {
      const j = src.indexOf('"', i + 1);
      if (j === -1) throw new Error(`${file}:${line}: unterminated string`);
      push('string', src.slice(i + 1, j));
      i = j + 1;
      continue;
    }
    if (c === '-' && src[i + 1] === '>') { push('punct', '->'); i += 2; continue; }
    if ('{}[]();:=?,.'.includes(c)) { push('punct', c); i++; continue; }
    throw new Error(`${file}:${line}: unexpected character '${c}'`);
  }
  toks.push({ type: 'eof', value: null, line, file, doc: [] });
  return toks;
}

// ─────────────────────────────────────────────────────────────────────────────
// Parser
// ─────────────────────────────────────────────────────────────────────────────

const SCALARS = new Set(['bool', 'i32', 'u32', 'i64', 'u64', 'f32', 'f64', 'string', 'bytes']);

function parse(files) {
  const model = {
    version: null,
    aliases: new Map(),
    enums: new Map(),
    structs: new Map(),
    unions: new Map(),
    commands: [],
    queries: [],
    events: [],
    order: [],
  };
  for (const { name, src } of files) {
    const toks = lex(src, name);
    let p = 0;
    let family = 'General';
    const peek = () => toks[p];
    const next = () => toks[p++];
    const where = (t) => `${t.file}:${t.line}`;
    const expect = (type, value) => {
      const t = next();
      if (t.type !== type || (value !== undefined && t.value !== value)) {
        throw new Error(`${where(t)}: expected ${value ?? type}, got ${t.value ?? t.type}`);
      }
      return t;
    };
    const accept = (type, value) => {
      const t = peek();
      if (t.type === type && (value === undefined || t.value === value)) { p++; return t; }
      return null;
    };
    const parseType = () => {
      const t = expect('ident');
      let list = false;
      if (accept('punct', '[')) { expect('punct', ']'); list = true; }
      return { name: t.value, list };
    };
    const parseFields = (owner) => {
      const fields = [];
      expect('punct', '{');
      while (!accept('punct', '}')) {
        const nameTok = expect('ident');
        const optional = !!accept('punct', '?');
        expect('punct', ':');
        const type = parseType();
        expect('punct', '=');
        const num = expect('int').value;
        expect('punct', ';');
        fields.push({ name: nameTok.value, optional, type, num, doc: nameTok.doc, where: where(nameTok) });
      }
      checkNums(fields, owner);
      return fields;
    };
    const parseAttrs = () => {
      const attrs = new Set();
      if (accept('punct', '[')) {
        do { attrs.add(expect('ident').value); } while (accept('punct', ','));
        expect('punct', ']');
      }
      return attrs;
    };
    while (peek().type !== 'eof') {
      const kw = expect('ident');
      const doc = kw.doc;
      switch (kw.value) {
        case 'version': {
          const major = expect('int').value;
          expect('punct', '.');
          const minor = expect('int').value;
          expect('punct', ';');
          if (model.version) throw new Error(`${where(kw)}: version declared twice`);
          model.version = { major, minor };
          break;
        }
        case 'family': {
          family = expect('string').value;
          expect('punct', ';');
          break;
        }
        case 'alias': {
          const n = expect('ident').value;
          expect('punct', '=');
          const target = expect('ident').value;
          expect('punct', ';');
          if (!SCALARS.has(target)) throw new Error(`${where(kw)}: alias ${n} must name a scalar`);
          define(model, n, where(kw));
          model.aliases.set(n, { name: n, target, doc });
          break;
        }
        case 'enum': {
          const n = expect('ident').value;
          define(model, n, where(kw));
          expect('punct', '{');
          const members = [];
          while (!accept('punct', '}')) {
            const t = next();
            if (t.type !== 'ident' && t.type !== 'string') throw new Error(`${where(t)}: enum member expected`);
            expect('punct', '=');
            const num = expect('int').value;
            expect('punct', ';');
            members.push({ name: t.value, num, doc: t.doc });
          }
          checkNums(members, n);
          if (!members.some((m) => m.num === 0)) throw new Error(`${where(kw)}: enum ${n} needs a member = 0 (the default)`);
          model.enums.set(n, { name: n, members, doc, family });
          model.order.push({ kind: 'enum', name: n });
          break;
        }
        case 'struct': {
          const n = expect('ident').value;
          define(model, n, where(kw));
          const fields = parseFields(n);
          model.structs.set(n, { name: n, fields, doc, family });
          model.order.push({ kind: 'struct', name: n });
          break;
        }
        case 'union': {
          const n = expect('ident').value;
          define(model, n, where(kw));
          const flat = !!accept('ident', 'flat');
          expect('punct', '{');
          const variants = [];
          while (!accept('punct', '}')) {
            const vt = expect('ident');
            expect('punct', ':');
            const type = expect('ident').value;
            expect('punct', '=');
            const num = expect('int').value;
            expect('punct', ';');
            variants.push({ name: vt.value, type, num, doc: vt.doc });
          }
          checkNums(variants, n);
          model.unions.set(n, { name: n, variants, flat, doc, family });
          model.order.push({ kind: 'union', name: n });
          break;
        }
        case 'command':
        case 'query':
        case 'event': {
          const nameTok = expect('ident');
          const n = nameTok.value;
          expect('punct', '=');
          const id = expect('int').value;
          const attrs = parseAttrs();
          const fields = parseFields(n);
          let result = null;
          if (accept('punct', '->')) result = expect('ident').value;
          accept('punct', ';');
          const typeName = kw.value === 'event' ? `${pascal(n)}Event` : pascal(n);
          define(model, typeName, where(kw));
          model.structs.set(typeName, { name: typeName, fields, doc, family, synthetic: kw.value });
          model.order.push({ kind: 'struct', name: typeName });
          const entry = { name: n, typeName, id, attrs, result, doc, family, where: where(kw) };
          if (kw.value === 'command') model.commands.push(entry);
          else if (kw.value === 'query') {
            if (!result) throw new Error(`${where(kw)}: query ${n} needs '-> ResultType'`);
            model.queries.push(entry);
          } else model.events.push(entry);
          break;
        }
        default:
          throw new Error(`${where(kw)}: unknown declaration '${kw.value}'`);
      }
    }
  }
  if (!model.version) throw new Error('schema: no `version major.minor;` declaration');
  synthesize(model);
  validate(model);
  return model;
}

function define(model, n, at) {
  if (model.aliases.has(n) || model.enums.has(n) || model.structs.has(n) || model.unions.has(n) || SCALARS.has(n)) {
    throw new Error(`${at}: '${n}' is already defined`);
  }
}

function checkNums(items, owner) {
  const seenNum = new Map();
  const seenName = new Set();
  for (const it of items) {
    if (seenNum.has(it.num)) throw new Error(`${owner}: number ${it.num} used by both ${seenNum.get(it.num)} and ${it.name}`);
    if (seenName.has(it.name)) throw new Error(`${owner}: duplicate name ${it.name}`);
    seenNum.set(it.num, it.name);
    seenName.add(it.name);
  }
}

/** The four top-level unions are derived from the command/query/event declarations. */
function synthesize(model) {
  const EMPTY = 'Empty';
  if (!model.structs.has(EMPTY)) throw new Error('schema: struct Empty {} must be declared');
  const mk = (name, entries, typeOf, doc) => {
    if (model.unions.has(name)) throw new Error(`schema: ${name} is synthesized; do not declare it`);
    model.unions.set(name, {
      name,
      flat: true,
      doc,
      family: 'Envelope',
      synthetic: true,
      variants: entries.map((e) => ({ name: e.name, type: typeOf(e), num: e.id, doc: e.doc })),
    });
    checkNums(model.unions.get(name).variants, name);
    model.order.push({ kind: 'union', name });
  };
  mk('Command', model.commands, (e) => e.typeName, ['Every command, keyed by its schema id.']);
  mk('CommandResult', model.commands, (e) => e.result ?? EMPTY, ['The typed result of a successful command; same key as its command.']);
  mk('Query', model.queries, (e) => e.typeName, ['Every query, keyed by its schema id.']);
  mk('QueryResult', model.queries, (e) => e.result, ['The typed result of a query; same key as its query.']);
  mk('Event', model.events, (e) => e.typeName, ['Every change / status event, keyed by its schema id.']);
}

function validate(model) {
  const known = (n) => SCALARS.has(n) || model.aliases.has(n) || model.enums.has(n) || model.structs.has(n) || model.unions.has(n);
  for (const s of model.structs.values()) {
    for (const f of s.fields) {
      if (!known(f.type.name)) throw new Error(`${f.where}: unknown type ${f.type.name}`);
      if (f.optional && f.type.list) throw new Error(`${f.where}: a list cannot be optional (an empty list is absent)`);
      if (f.num < 1 || f.num > 536870911) throw new Error(`${f.where}: field number out of range`);
    }
  }
  for (const u of model.unions.values()) {
    for (const v of u.variants) {
      if (v.type !== 'void' && !known(v.type)) throw new Error(`union ${u.name}.${v.name}: unknown type ${v.type}`);
      if (u.flat && !model.structs.has(v.type)) throw new Error(`flat union ${u.name}.${v.name} must carry a struct`);
      if (u.flat && model.structs.get(v.type).fields.some((f) => f.name === 'type')) {
        throw new Error(`flat union ${u.name}: struct ${v.type} may not have a field named 'type'`);
      }
      if (v.num < 1) throw new Error(`union ${u.name}.${v.name}: variant number must be ≥ 1`);
    }
  }
  for (const c of model.commands) {
    for (const a of c.attrs) if (!['control', 'io', 'coalesce'].includes(a)) throw new Error(`${c.where}: unknown attribute ${a}`);
    if (c.result && !model.structs.has(c.result)) throw new Error(`${c.where}: result ${c.result} must be a struct`);
  }
  for (const q of model.queries) {
    if (q.attrs.size) throw new Error(`${q.where}: queries take no attributes`);
    if (!model.structs.has(q.result)) throw new Error(`${q.where}: result ${q.result} must be a struct`);
  }
  for (const e of model.events) {
    for (const a of e.attrs) if (a !== 'ephemeral') throw new Error(`${e.where}: unknown attribute ${a}`);
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// Type helpers shared by every backend
// ─────────────────────────────────────────────────────────────────────────────

function pascal(s) { return s[0].toUpperCase() + s.slice(1); }
function snake(s) {
  return s.replace(/-/g, '_').replace(/([a-z0-9])([A-Z])/g, '$1_$2').replace(/([A-Z]+)([A-Z][a-z])/g, '$1_$2').toLowerCase();
}

/** Resolve aliases down to a scalar / named type. */
function base(model, n) { return model.aliases.has(n) ? model.aliases.get(n).target : n; }

/** 'varint' | 'svarint' | 'bool' | 'f32' | 'f64' | 'string' | 'bytes' | 'enum' | 'struct' | 'union' */
function category(model, n) {
  const b = base(model, n);
  switch (b) {
    case 'bool': return 'bool';
    case 'u32': case 'u64': return 'varint';
    case 'i32': case 'i64': return 'svarint';
    case 'f32': return 'f32';
    case 'f64': return 'f64';
    case 'string': return 'string';
    case 'bytes': return 'bytes';
    default:
      if (model.enums.has(b)) return 'enum';
      if (model.structs.has(b)) return 'struct';
      if (model.unions.has(b)) return 'union';
      throw new Error(`unknown type ${n}`);
  }
}

const WT = { varint: 0, svarint: 0, bool: 0, enum: 0, f64: 1, f32: 5, string: 2, bytes: 2, struct: 2, union: 2 };
function isPackable(cat) { return cat === 'varint' || cat === 'svarint' || cat === 'bool' || cat === 'enum' || cat === 'f32' || cat === 'f64'; }
function keyOf(num, cat, list) { return num * 8 + (list && isPackable(cat) ? 2 : WT[cat]); }

function sortedFields(s) { return [...s.fields].sort((a, b) => a.num - b.num); }
function sortedVariants(u) { return [...u.variants].sort((a, b) => a.num - b.num); }

function varintBytes(n) {
  const out = [];
  let v = n;
  while (v >= 128) { out.push((v % 128) + 128); v = Math.floor(v / 128); }
  out.push(v);
  return out;
}

// ─────────────────────────────────────────────────────────────────────────────
// Reflective encoder + sample values (fixtures, tests)
// ─────────────────────────────────────────────────────────────────────────────

function makeReflect(model) {
  const bytes = [];
  const pushVarint = (n) => { for (const b of varintBytes(n)) bytes.push(b); };
  const f64le = (x) => { const b = Buffer.alloc(8); b.writeDoubleLE(x); for (const v of b) bytes.push(v); };
  const f32le = (x) => { const b = Buffer.alloc(4); b.writeFloatLE(x); for (const v of b) bytes.push(v); };
  const zig = (n) => (n >= 0 ? n * 2 : -n * 2 - 1);
  const ld = (fn) => {
    const start = bytes.length;
    fn();
    const body = bytes.splice(start);
    pushVarint(body.length);
    for (const b of body) bytes.push(b);
  };
  const enumNum = (t, v) => {
    const m = model.enums.get(base(model, t)).members.find((x) => x.name === v);
    if (!m) throw new Error(`enum ${t}: no member ${v}`);
    return m.num;
  };
  const scalar = (cat, t, v) => {
    switch (cat) {
      case 'bool': pushVarint(v ? 1 : 0); break;
      case 'varint': pushVarint(v); break;
      case 'svarint': pushVarint(zig(v)); break;
      case 'enum': pushVarint(enumNum(t, v)); break;
      case 'f32': f32le(v); break;
      case 'f64': f64le(v); break;
      case 'string': { const b = Buffer.from(v, 'utf8'); pushVarint(b.length); for (const x of b) bytes.push(x); break; }
      case 'bytes': pushVarint(v.length); for (const x of v) bytes.push(x); break;
      default: throw new Error(cat);
    }
  };
  const value = (t, v) => {
    const cat = category(model, t);
    if (cat === 'struct') ld(() => struct(base(model, t), v));
    else if (cat === 'union') ld(() => union(base(model, t), v));
    else scalar(cat, t, v);
  };
  const struct = (n, v) => {
    for (const f of sortedFields(model.structs.get(n))) {
      const cat = category(model, f.type.name);
      const x = v[f.name];
      if (f.type.list) {
        if (!x || x.length === 0) continue;
        if (isPackable(cat)) {
          pushVarint(keyOf(f.num, cat, true));
          ld(() => { for (const e of x) scalar(cat, f.type.name, e); });
        } else {
          for (const e of x) { pushVarint(keyOf(f.num, cat, false)); value(f.type.name, e); }
        }
        continue;
      }
      if (x === undefined) {
        if (f.optional) continue;
        throw new Error(`reflect: ${n}.${f.name} is required`);
      }
      pushVarint(keyOf(f.num, cat, false));
      value(f.type.name, x);
    }
  };
  const union = (n, v) => {
    const u = model.unions.get(n);
    const tag = u.flat ? v.type : v.kind;
    const variant = u.variants.find((x) => x.name === tag);
    if (!variant) throw new Error(`reflect: ${n} has no variant ${tag}`);
    if (variant.type === 'void') { pushVarint(variant.num * 8 + 2); pushVarint(0); return; }
    const cat = category(model, variant.type);
    pushVarint(keyOf(variant.num, cat, false));
    value(variant.type, u.flat ? v : v.value);
  };
  return {
    encode(typeName, v) {
      bytes.length = 0;
      const cat = category(model, typeName);
      if (cat === 'struct') struct(base(model, typeName), v);
      else if (cat === 'union') union(base(model, typeName), v);
      else throw new Error('reflect.encode takes a struct or union');
      return Uint8Array.from(bytes);
    },
  };
}

/** Deterministic PRNG (mulberry32) seeded from a string. */
function rng(seedText) {
  let h = 2166136261;
  for (let i = 0; i < seedText.length; i++) { h ^= seedText.charCodeAt(i); h = Math.imul(h, 16777619); }
  let a = h >>> 0;
  return () => {
    a = (a + 0x6d2b79f5) >>> 0;
    let t = a;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

const SAMPLE_STRINGS = ['layer-7f3a', 'Comp 1', 'effects/fx_12/params/radius', 'é漢字😀', '', 'transform/position'];

/**
 * Sample values for a type. `mode` 'full' fills every optional field and gives
 * every list two entries; 'min' leaves optionals absent and lists empty.
 * Recursion is cut off by depth (a list of itself becomes empty).
 */
function makeSampler(model) {
  const sampleScalar = (r, t) => {
    const b = base(model, t);
    switch (b) {
      case 'bool': return r() < 0.5;
      case 'u32': return Math.floor(r() * 4294967295);
      case 'i32': return Math.floor(r() * 4294967295) - 2147483648;
      case 'u64': return Math.floor(r() * 2 ** 53);
      case 'i64': return Math.floor(r() * 2 ** 53) - 2 ** 52;
      case 'f32': return Math.fround((r() - 0.5) * 1e6);
      case 'f64': return (r() - 0.5) * 1e9;
      case 'string': return SAMPLE_STRINGS[Math.floor(r() * SAMPLE_STRINGS.length)];
      case 'bytes': return Uint8Array.from([0, 1, 255, Math.floor(r() * 256)]);
      default: {
        const e = model.enums.get(b);
        return e.members[Math.floor(r() * e.members.length)].name;
      }
    }
  };
  const sample = (r, t, mode, depth, pick) => {
    const cat = category(model, t);
    const b = base(model, t);
    if (cat === 'struct') {
      const s = model.structs.get(b);
      const o = {};
      for (const f of s.fields) {
        if (f.type.list) {
          const n = mode === 'full' && depth < 3 ? 2 : 0;
          o[f.name] = Array.from({ length: n }, () => sample(r, f.type.name, mode, depth + 1));
        } else if (!f.optional || mode === 'full') {
          o[f.name] = sample(r, f.type.name, mode, depth + 1);
        }
      }
      return o;
    }
    if (cat === 'union') {
      const u = model.unions.get(b);
      const v = pick !== undefined ? u.variants[pick] : u.variants[Math.floor(r() * u.variants.length)];
      if (u.flat) return { type: v.name, ...sample(r, v.type, mode, depth + 1) };
      if (v.type === 'void') return { kind: v.name };
      return { kind: v.name, value: sample(r, v.type, mode, depth + 1) };
    }
    return sampleScalar(r, t);
  };
  return {
    /** Every sample for a named struct/union: full + min, and one per union variant. */
    samplesFor(typeName) {
      const out = [];
      const u = model.unions.get(typeName);
      if (u) {
        u.variants.forEach((v, i) => {
          out.push({ label: `${typeName}.${v.name}`, value: sample(rng(`${typeName}.${v.name}`), typeName, 'full', 0, i) });
          if (v.type !== 'void' && model.structs.has(v.type) && model.structs.get(v.type).fields.length) {
            out.push({ label: `${typeName}.${v.name}#min`, value: sample(rng(`${typeName}.${v.name}#min`), typeName, 'min', 0, i) });
          }
        });
      } else {
        out.push({ label: `${typeName}#full`, value: sample(rng(`${typeName}#full`), typeName, 'full', 0) });
        out.push({ label: `${typeName}#min`, value: sample(rng(`${typeName}#min`), typeName, 'min', 0) });
      }
      return out;
    },
  };
}

/** Every struct and union name, in declaration order (the round-trip set). */
function messageTypes(model) {
  return model.order.filter((o) => o.kind === 'struct' || o.kind === 'union').map((o) => o.name);
}

// ─────────────────────────────────────────────────────────────────────────────
// TypeScript backend
// ─────────────────────────────────────────────────────────────────────────────

function tsDoc(doc, indent = '') {
  if (!doc || doc.length === 0) return '';
  if (doc.length === 1) return `${indent}/** ${doc[0]} */\n`;
  return `${indent}/**\n${doc.map((d) => `${indent} * ${d}`.trimEnd()).join('\n')}\n${indent} */\n`;
}

function tsScalar(model, n) {
  switch (n) {
    case 'bool': return 'boolean';
    case 'string': return 'string';
    case 'bytes': return 'Uint8Array';
    case 'i32': case 'u32': case 'i64': case 'u64': case 'f32': case 'f64': return 'number';
    default: return n;
  }
}

function tsTypeRef(model, t) {
  const n = SCALARS.has(t.name) ? tsScalar(model, t.name) : t.name;
  return t.list ? `${n}[]` : n;
}

function genTsTypes(model) {
  let out = `/* eslint-disable */\n// ${HEADER_NOTE}\n\n`;
  out += `/** Protocol version this file was generated for. */\n`;
  out += `export const PROTOCOL_VERSION = { major: ${model.version.major}, minor: ${model.version.minor} } as const;\n\n`;
  for (const o of model.order) {
    if (o.kind === 'enum') {
      const e = model.enums.get(o.name);
      out += tsDoc(e.doc);
      out += `export type ${e.name} =\n${e.members.map((m) => `  | '${m.name}'`).join('\n')};\n`;
      out += `export const ${e.name}Values = [${e.members.map((m) => `'${m.name}'`).join(', ')}] as const;\n\n`;
    }
  }
  for (const a of model.aliases.values()) {
    out += tsDoc(a.doc);
    out += `export type ${a.name} = ${tsScalar(model, a.target)};\n\n`;
  }
  for (const o of model.order) {
    if (o.kind === 'struct') {
      const s = model.structs.get(o.name);
      out += tsDoc(s.doc);
      if (s.fields.length === 0) { out += `export interface ${s.name} {}\n\n`; continue; }
      out += `export interface ${s.name} {\n`;
      for (const f of s.fields) {
        out += tsDoc(f.doc, '  ');
        out += `  ${f.name}${f.optional ? '?' : ''}: ${tsTypeRef(model, f.type)};\n`;
      }
      out += `}\n\n`;
    } else if (o.kind === 'union') {
      const u = model.unions.get(o.name);
      out += tsDoc(u.doc);
      const arms = u.variants.map((v) => {
        if (u.flat) return `  | ({ type: '${v.name}' } & ${v.type})`;
        if (v.type === 'void') return `  | { kind: '${v.name}' }`;
        return `  | { kind: '${v.name}'; value: ${SCALARS.has(v.type) ? tsScalar(model, v.type) : v.type} }`;
      });
      out += `export type ${u.name} =\n${arms.join('\n')};\n`;
      out += `export type ${u.name}${u.flat ? 'Type' : 'Kind'} = ${u.name}['${u.flat ? 'type' : 'kind'}'];\n\n`;
    }
  }
  // Convenience maps: command → args / result types.
  out += `/** Arguments of each command, by name. */\nexport interface CommandArgs {\n${model.commands.map((c) => `  ${c.name}: ${c.typeName};`).join('\n')}\n}\n\n`;
  out += `/** Result of each command, by name. */\nexport interface CommandResults {\n${model.commands.map((c) => `  ${c.name}: ${c.result ?? 'Empty'};`).join('\n')}\n}\n\n`;
  out += `/** Arguments of each query, by name. */\nexport interface QueryArgs {\n${model.queries.map((c) => `  ${c.name}: ${c.typeName};`).join('\n')}\n}\n\n`;
  out += `/** Result of each query, by name. */\nexport interface QueryResults {\n${model.queries.map((c) => `  ${c.name}: ${c.result};`).join('\n')}\n}\n\n`;
  out += `/** Payload of each event, by name. */\nexport interface EventPayloads {\n${model.events.map((c) => `  ${c.name}: ${c.typeName};`).join('\n')}\n}\n`;
  return out;
}

/**
 * The TypeScript codec. `opts` exists for the standalone family modules
 * (genTsFamilyModule): a different wire-runtime import, types declared in the
 * same file (prefix ''), and no EngineMessage helpers.
 */
function genTsCodec(model, opts = {}) {
  const { wireImport = '../wire', typesImport = './types', envelope = true, header = true } = opts;
  const TP = typesImport ? 'T.' : '';
  const L = [];
  if (header) {
    L.push('/* eslint-disable */');
    L.push(`// ${HEADER_NOTE}`);
    L.push('');
  }
  L.push(`import { Reader, Writer, DecodeError } from '${wireImport}';`);
  const typeNames = messageTypes(model);
  if (typesImport) L.push(`import type * as T from '${typesImport}';`);
  L.push('');

  // Enum tables.
  for (const e of model.enums.values()) {
    L.push(`const ${e.name}_TO_NUM: Record<string, number> = { ${e.members.map((m) => `'${m.name}': ${m.num}`).join(', ')} };`);
    const maxNum = Math.max(...e.members.map((m) => m.num));
    const arr = new Array(maxNum + 1).fill('undefined');
    for (const m of e.members) arr[m.num] = `'${m.name}'`;
    L.push(`const ${e.name}_FROM_NUM: readonly (${TP}${e.name} | undefined)[] = [${arr.join(', ')}];`);
    L.push(`function enc_${e.name}(v: ${TP}${e.name}): number { const n = ${e.name}_TO_NUM[v]; if (n === undefined) throw new RangeError('${e.name}: invalid value ' + String(v)); return n; }`);
    L.push(`function dec_${e.name}(n: number): ${TP}${e.name} { const v = ${e.name}_FROM_NUM[n]; if (v === undefined) throw new DecodeError('${e.name}: unknown value ' + n, 'badEnum'); return v; }`);
  }
  L.push('');

  const tsT = (n) => {
    const b = base(model, n);
    if (SCALARS.has(b)) return tsScalar(model, b);
    return `${TP}${b}`;
  };
  const writeScalar = (cat, t, expr) => {
    const b = base(model, t);
    switch (cat) {
      case 'bool': return `w.bool(${expr});`;
      case 'varint': return b === 'u32' ? `w.u32(${expr});` : `w.u64(${expr});`;
      case 'svarint': return b === 'i32' ? `w.i32(${expr});` : `w.i64(${expr});`;
      case 'enum': return `w.varint(enc_${b}(${expr}));`;
      case 'f32': return `w.f32(${expr});`;
      case 'f64': return `w.f64(${expr});`;
      case 'string': return `w.str(${expr});`;
      case 'bytes': return `w.bytes(${expr});`;
    }
    throw new Error(cat);
  };
  const readScalar = (cat, t) => {
    const b = base(model, t);
    switch (cat) {
      case 'bool': return 'r.bool()';
      case 'varint': return b === 'u32' ? 'r.u32()' : 'r.u64()';
      case 'svarint': return b === 'i32' ? 'r.i32()' : 'r.i64()';
      case 'enum': return `dec_${b}(r.varint())`;
      case 'f32': return 'r.f32()';
      case 'f64': return 'r.f64()';
      case 'string': return 'r.str()';
      case 'bytes': return 'r.bytes()';
    }
    throw new Error(cat);
  };
  const writeKey = (key) => (key < 128 ? `w.byte(${key});` : `w.varint(${key});`);
  const writeValue = (t, expr) => {
    const cat = category(model, t);
    const b = base(model, t);
    if (cat === 'struct' || cat === 'union') return `{ const s = w.beginLd(); enc${cat === 'struct' ? 'S' : 'U'}_${b}(w, ${expr}); w.endLd(s); }`;
    return writeScalar(cat, t, expr);
  };
  const readValue = (t) => {
    const cat = category(model, t);
    const b = base(model, t);
    if (cat === 'struct') return `decS_${b}(r, r.ldEnd(), {})`;
    if (cat === 'union') return `decU_${b}(r, r.ldEnd())`;
    return readScalar(cat, t);
  };

  for (const s of model.structs.values()) {
    const fs = sortedFields(s);
    // encoder
    L.push(`function encS_${s.name}(w: Writer, v: ${TP}${s.name}): void {`);
    if (fs.length === 0) L.push('  void w; void v;');
    for (const f of fs) {
      const cat = category(model, f.type.name);
      const acc = `v.${f.name}`;
      if (f.type.list) {
        if (isPackable(cat)) {
          const key = keyOf(f.num, cat, true);
          if (cat === 'f64' || cat === 'f32') {
            const sz = cat === 'f64' ? 8 : 4;
            L.push(`  { const a = ${acc}; if (a.length) { ${writeKey(key)} w.varint(a.length * ${sz}); for (let i = 0; i < a.length; i++) w.${cat}(a[i]!); } }`);
          } else {
            L.push(`  { const a = ${acc}; if (a.length) { ${writeKey(key)} const s = w.beginLd(); for (let i = 0; i < a.length; i++) ${writeScalar(cat, f.type.name, 'a[i]!')} w.endLd(s); } }`);
          }
        } else {
          const key = keyOf(f.num, cat, false);
          L.push(`  { const a = ${acc}; for (let i = 0; i < a.length; i++) { ${writeKey(key)} ${writeValue(f.type.name, 'a[i]!')} } }`);
        }
      } else {
        const key = keyOf(f.num, cat, false);
        const body = `${writeKey(key)} ${writeValue(f.type.name, acc)}`;
        if (f.optional) L.push(`  if (${acc} !== undefined) { ${body} }`);
        else L.push(`  ${body}`);
      }
    }
    L.push('}');
    // decoder: fills `o` (so a flat union can pre-seed its `type`)
    L.push(`function decS_${s.name}(r: Reader, end: number, o: any): ${TP}${s.name} {`);
    for (const f of fs) if (f.type.list) L.push(`  const l_${f.name}: ${tsT(f.type.name)}[] = [];`);
    const req = fs.filter((f) => !f.type.list && !f.optional);
    for (const f of req) L.push(`  let h_${f.name} = false;`);
    for (const f of fs) if (!f.type.list) L.push(`  let v_${f.name}: ${tsT(f.type.name)} | undefined;`);
    L.push('  while (r.pos < end) {');
    L.push('    const key = r.varint();');
    L.push('    switch (key) {');
    for (const f of fs) {
      const cat = category(model, f.type.name);
      if (f.type.list) {
        if (isPackable(cat)) {
          L.push(`      case ${keyOf(f.num, cat, true)}: { const e = r.ldEnd(); while (r.pos < e) l_${f.name}.push(${readScalar(cat, f.type.name)}); r.expectAt(e); break; }`);
        } else {
          L.push(`      case ${keyOf(f.num, cat, false)}: l_${f.name}.push(${readValue(f.type.name)}); break;`);
        }
      } else {
        const set = req.includes(f) ? ` h_${f.name} = true;` : '';
        L.push(`      case ${keyOf(f.num, cat, false)}: v_${f.name} = ${readValue(f.type.name)};${set} break;`);
      }
    }
    L.push('      default: r.skip(key);');
    L.push('    }');
    L.push('  }');
    L.push(`  r.expectAt(end);`);
    for (const f of req) L.push(`  if (!h_${f.name}) throw new DecodeError('${s.name}.${f.name}: missing', 'missingField');`);
    for (const f of fs) {
      if (f.type.list) L.push(`  o.${f.name} = l_${f.name};`);
      else if (f.optional) L.push(`  if (v_${f.name} !== undefined) o.${f.name} = v_${f.name};`);
      else L.push(`  o.${f.name} = v_${f.name};`);
    }
    L.push('  return o;');
    L.push('}');
  }

  for (const u of model.unions.values()) {
    const vs = sortedVariants(u);
    const tag = u.flat ? 'type' : 'kind';
    L.push(`function encU_${u.name}(w: Writer, v: ${TP}${u.name}): void {`);
    L.push(`  switch (v.${tag}) {`);
    for (const x of vs) {
      if (x.type === 'void') { L.push(`    case '${x.name}': w.varint(${x.num * 8 + 2}); w.byte(0); return;`); continue; }
      const cat = category(model, x.type);
      const key = keyOf(x.num, cat, false);
      const expr = u.flat ? 'v' : 'v.value';
      L.push(`    case '${x.name}': ${writeKey(key)} ${writeValue(x.type, expr)} return;`);
    }
    L.push(`    default: throw new RangeError('${u.name}: unknown ${tag} ' + String((v as { ${tag}?: unknown }).${tag}));`);
    L.push('  }');
    L.push('}');
    L.push(`function decU_${u.name}(r: Reader, end: number): ${TP}${u.name} {`);
    L.push(`  let out: ${TP}${u.name} | undefined;`);
    L.push('  while (r.pos < end) {');
    L.push('    const key = r.varint();');
    L.push(`    if (out !== undefined && key >>> 3 !== 0) throw new DecodeError('${u.name}: more than one variant');`);
    L.push('    switch (key) {');
    for (const x of vs) {
      if (x.type === 'void') {
        L.push(`      case ${x.num * 8 + 2}: { const e = r.ldEnd(); r.pos = e; out = { kind: '${x.name}' } as ${TP}${u.name}; break; }`);
        continue;
      }
      const cat = category(model, x.type);
      const key = keyOf(x.num, cat, false);
      if (u.flat) {
        L.push(`      case ${key}: out = decS_${base(model, x.type)}(r, r.ldEnd(), { type: '${x.name}' }) as ${TP}${u.name}; break;`);
      } else {
        L.push(`      case ${key}: out = { kind: '${x.name}', value: ${readValue(x.type)} } as ${TP}${u.name}; break;`);
      }
    }
    L.push('      default: r.skip(key);');
    L.push('    }');
    L.push('  }');
    L.push('  r.expectAt(end);');
    L.push(`  if (out === undefined) throw new DecodeError('${u.name}: no known variant (newer peer?)', 'unknownVariant');`);
    L.push('  return out;');
    L.push('}');
  }
  L.push('');

  // Public codec table.
  L.push('/** Encode / decode any schema struct or union as a standalone message. */');
  L.push('export interface Codec<V> { encode(v: V): Uint8Array; decode(bytes: Uint8Array): V; }');
  L.push('');
  L.push('const shared = new Writer(1024);');
  L.push('function mk<V>(enc: (w: Writer, v: V) => void, dec: (r: Reader, end: number) => V): Codec<V> {');
  L.push('  return {');
  L.push('    encode(v: V): Uint8Array { shared.reset(); enc(shared, v); return shared.finish(); },');
  L.push('    decode(bytes: Uint8Array): V { const r = new Reader(bytes); return dec(r, bytes.length); },');
  L.push('  };');
  L.push('}');
  L.push('');
  L.push('export const codecs = {');
  for (const n of typeNames) {
    if (model.structs.has(n)) L.push(`  ${n}: mk<${TP}${n}>(encS_${n}, (r, e) => decS_${n}(r, e, {})),`);
    else L.push(`  ${n}: mk<${TP}${n}>(encU_${n}, decU_${n}),`);
  }
  L.push('} as const;');
  L.push('');
  L.push('export type CodecName = keyof typeof codecs;');
  if (!envelope) return L.join('\n') + '\n';
  L.push('');
  L.push('/** Encode into a caller-owned writer (no copy); the transport frames it. */');
  L.push('export function encodeEngineMessageInto(w: Writer, v: T.EngineMessage): void { encU_EngineMessage(w, v); }');
  L.push('export const encodeEngineMessage = (v: T.EngineMessage): Uint8Array => codecs.EngineMessage.encode(v);');
  L.push('export const decodeEngineMessage = (bytes: Uint8Array): T.EngineMessage => codecs.EngineMessage.decode(bytes);');
  return L.join('\n') + '\n';
}

/**
 * A self-contained TypeScript module for ONE schema family: its types and codec
 * in one file, importing the wire runtime from `wireImport`. For code that
 * cannot import packages/engine-api — Electron main is its own CommonJS
 * TypeScript project (electron/tsconfig.json, rootDir `.`), and it speaks the
 * frame channel itself. The family must be closed: it may reference scalars,
 * aliases and its own types only.
 */
function genTsFamilyModule(model, family, wireImport) {
  const own = (m) => [...m.values()].filter((x) => x.family === family && !x.synthetic);
  const enums = own(model.enums);
  const structs = own(model.structs);
  const unions = own(model.unions);
  if (!structs.length && !unions.length) throw new Error(`family ${family}: nothing to generate`);
  const names = new Set([...enums, ...structs, ...unions].map((x) => x.name));
  const needAlias = new Set();
  const check = (t, where) => {
    if (SCALARS.has(t) || t === 'void' || names.has(t)) return;
    if (model.aliases.has(t)) { needAlias.add(t); return; }
    throw new Error(`family ${family} is not closed: ${where} references ${t}`);
  };
  for (const s of structs) for (const f of s.fields) check(f.type.name, `${s.name}.${f.name}`);
  for (const u of unions) for (const v of u.variants) check(v.type, `${u.name}.${v.name}`);
  const sub = {
    version: model.version,
    aliases: new Map([...model.aliases].filter(([n]) => needAlias.has(n))),
    enums: new Map(enums.map((e) => [e.name, e])),
    structs: new Map(structs.map((s) => [s.name, s])),
    unions: new Map(unions.map((u) => [u.name, u])),
    commands: [],
    queries: [],
    events: [],
    order: model.order.filter((o) => names.has(o.name)),
  };
  let out = `/* eslint-disable */\n// ${HEADER_NOTE}\n//\n// Family "${family}" only — a standalone copy for code that cannot import packages/engine-api.\n\n`;
  // Types: everything genTsTypes emits except the command/query/event maps (none here).
  const types = genTsTypes(sub).split('/** Arguments of each command, by name. */')[0].replace(/^\/\* eslint-disable \*\/\n\/\/ .*\n\n/, '');
  const [importLine, ...codec] = genTsCodec(sub, { wireImport, typesImport: null, envelope: false, header: false }).split('\n');
  out += `${importLine}\n\n`;
  out += types.trimEnd() + '\n';
  out += codec.join('\n');
  return out;
}

/** The wire runtime, copied for a standalone family module's project. */
function genTsWireCopy() {
  const src = readFileSync(join(__dirname, '..', 'src', 'wire.ts'), 'utf8').replace(/\r\n/g, '\n');
  return `// COPIED by packages/engine-api/codegen/generate.cjs from packages/engine-api/src/wire.ts — do not edit; run \`npm run engine-api:gen\`.\n\n${src}`;
}

function genTsMeta(model) {
  const L = [];
  L.push(`// ${HEADER_NOTE}`);
  L.push('');
  L.push(`import type { CommandType, QueryType, EventType } from './types';`);
  L.push('');
  L.push('/**');
  L.push(' * How a command relates to history:');
  L.push(' *  - edit     changes the document; one undo entry (or part of the open gesture / batch)');
  L.push(' *  - control  history, gestures, transport, viewport, session — never an undo entry');
  L.push(' *  - io       project lifecycle (open/save/new) — not undoable, clears or keeps history as documented');
  L.push(' */');
  L.push(`export type CommandKind = 'edit' | 'control' | 'io';`);
  L.push('');
  L.push('export interface CommandInfo { readonly id: number; readonly kind: CommandKind; readonly coalesce: boolean; readonly family: string; readonly result: string; readonly doc: string; }');
  L.push('export interface QueryInfo { readonly id: number; readonly family: string; readonly result: string; readonly doc: string; }');
  L.push('export interface EventInfo { readonly id: number; readonly ephemeral: boolean; readonly family: string; readonly doc: string; }');
  L.push('');
  const q = (s) => JSON.stringify(s);
  L.push('export const COMMANDS: Readonly<Record<CommandType, CommandInfo>> = {');
  for (const c of model.commands) {
    const kind = c.attrs.has('control') ? 'control' : c.attrs.has('io') ? 'io' : 'edit';
    L.push(`  ${c.name}: { id: ${c.id}, kind: '${kind}', coalesce: ${c.attrs.has('coalesce')}, family: ${q(c.family)}, result: ${q(c.result ?? 'Empty')}, doc: ${q(c.doc.join(' '))} },`);
  }
  L.push('};');
  L.push('');
  L.push('export const QUERIES: Readonly<Record<QueryType, QueryInfo>> = {');
  for (const c of model.queries) L.push(`  ${c.name}: { id: ${c.id}, family: ${q(c.family)}, result: ${q(c.result)}, doc: ${q(c.doc.join(' '))} },`);
  L.push('};');
  L.push('');
  L.push('export const EVENTS: Readonly<Record<EventType, EventInfo>> = {');
  for (const c of model.events) L.push(`  ${c.name}: { id: ${c.id}, ephemeral: ${c.attrs.has('ephemeral')}, family: ${q(c.family)}, doc: ${q(c.doc.join(' '))} },`);
  L.push('};');
  L.push('');
  const counts = { enums: model.enums.size, structs: model.structs.size, unions: model.unions.size, commands: model.commands.length, queries: model.queries.length, events: model.events.length };
  L.push(`/** Size of the schema, for docs and tests. */`);
  L.push(`export const SCHEMA_COUNTS = ${JSON.stringify(counts)} as const;`);
  return L.join('\n') + '\n';
}

// ─────────────────────────────────────────────────────────────────────────────
// C++ backend
// ─────────────────────────────────────────────────────────────────────────────

const CPP_KEYWORDS = new Set(['alignas', 'alignof', 'and', 'and_eq', 'asm', 'auto', 'bitand', 'bitor', 'bool', 'break', 'case', 'catch', 'char', 'class', 'compl', 'concept', 'const', 'consteval', 'constexpr', 'constinit', 'const_cast', 'continue', 'co_await', 'co_return', 'co_yield', 'decltype', 'default', 'delete', 'do', 'double', 'dynamic_cast', 'else', 'enum', 'explicit', 'export', 'extern', 'false', 'float', 'for', 'friend', 'goto', 'if', 'inline', 'int', 'long', 'mutable', 'namespace', 'new', 'noexcept', 'not', 'not_eq', 'nullptr', 'operator', 'or', 'or_eq', 'private', 'protected', 'public', 'register', 'reinterpret_cast', 'requires', 'return', 'short', 'signed', 'sizeof', 'static', 'static_assert', 'static_cast', 'struct', 'switch', 'template', 'this', 'thread_local', 'throw', 'true', 'try', 'typedef', 'typeid', 'typename', 'union', 'unsigned', 'using', 'virtual', 'void', 'volatile', 'wchar_t', 'while', 'xor', 'xor_eq', 'min', 'max', 'small', 'near', 'far', 'errno', 'stdin', 'stdout', 'stderr', 'EOF', 'NULL', 'DELETE', 'IN', 'OUT', 'ERROR', 'OPTIONAL', 'TRUE', 'FALSE']);
function cppIdent(n) { const s = snake(n); return CPP_KEYWORDS.has(s) ? `${s}_` : s; }

function cppScalar(n) {
  switch (n) {
    case 'bool': return 'bool';
    case 'i32': return 'std::int32_t';
    case 'u32': return 'std::uint32_t';
    case 'i64': return 'std::int64_t';
    case 'u64': return 'std::uint64_t';
    case 'f32': return 'float';
    case 'f64': return 'double';
    case 'string': return 'std::string';
    case 'bytes': return 'std::vector<std::uint8_t>';
  }
  return null;
}

function cppT(model, n) { return cppScalar(n) ?? n; }

function cppDefault(model, n) {
  const b = base(model, n);
  switch (b) {
    case 'bool': return ' = false';
    case 'i32': case 'u32': case 'i64': case 'u64': return ' = 0';
    case 'f32': return ' = 0.0F';
    case 'f64': return ' = 0.0';
    default:
      if (model.enums.has(b)) {
        const e = model.enums.get(b);
        return ` = ${b}::${cppIdent(e.members.find((m) => m.num === 0).name)}`;
      }
      return '';
  }
}

/** Topological order so by-value members are complete; list edges are soft (std::vector allows incomplete T). */
function cppOrder(model) {
  const deps = new Map();
  const add = (n, d) => deps.get(n).add(d);
  for (const s of model.structs.values()) {
    deps.set(s.name, new Set());
  }
  for (const u of model.unions.values()) deps.set(u.name, new Set());
  for (const s of model.structs.values()) {
    for (const f of s.fields) {
      const b = base(model, f.type.name);
      if ((model.structs.has(b) || model.unions.has(b)) && !f.type.list) add(s.name, b);
      if ((model.structs.has(b) || model.unions.has(b)) && f.type.list && b !== s.name) add(s.name, b);
    }
  }
  for (const u of model.unions.values()) {
    for (const v of u.variants) {
      const b = v.type === 'void' ? null : base(model, v.type);
      if (b && (model.structs.has(b) || model.unions.has(b))) add(u.name, b);
    }
  }
  const out = [];
  const state = new Map();
  const visit = (n, chain) => {
    if (state.get(n) === 2) return;
    if (state.get(n) === 1) throw new Error(`C++: by-value cycle ${[...chain, n].join(' → ')}`);
    state.set(n, 1);
    for (const d of deps.get(n)) visit(d, [...chain, n]);
    state.set(n, 2);
    out.push(n);
  };
  for (const o of model.order) if (o.kind !== 'enum') visit(o.name, []);
  return out;
}

function genCppHeader(model) {
  const L = [];
  L.push(`// ${HEADER_NOTE}`);
  L.push('//');
  L.push('// Plain structs + a canonical binary codec for the Premation engine API');
  L.push('// (docs/ENGINE_API.md). No exceptions: decode returns a wire::Status.');
  L.push('');
  L.push('#ifndef PREMATION_PROTOCOL_ENGINE_API_HPP');
  L.push('#define PREMATION_PROTOCOL_ENGINE_API_HPP');
  L.push('');
  L.push('#include <cstdint>');
  L.push('#include <optional>');
  L.push('#include <span>');
  L.push('#include <string>');
  L.push('#include <string_view>');
  L.push('#include <variant>');
  L.push('#include <vector>');
  L.push('');
  L.push('#include "premation/protocol/wire.hpp"');
  L.push('');
  L.push('namespace premation::api {');
  L.push('');
  L.push(`inline constexpr std::uint32_t kProtocolMajor = ${model.version.major};`);
  L.push(`inline constexpr std::uint32_t kProtocolMinor = ${model.version.minor};`);
  L.push('');
  for (const a of model.aliases.values()) L.push(`using ${a.name} = ${cppScalar(a.target)};`);
  L.push('');
  for (const e of model.enums.values()) {
    L.push(`enum class ${e.name} : std::uint32_t {`);
    for (const m of e.members) L.push(`  ${cppIdent(m.name)} = ${m.num},`);
    L.push('};');
    L.push(`[[nodiscard]] std::string_view to_string(${e.name} v) noexcept;`);
    L.push(`[[nodiscard]] bool from_u32(std::uint32_t n, ${e.name}& out) noexcept;`);
    L.push('');
  }
  const order = cppOrder(model);
  for (const n of order) L.push(`struct ${n};`);
  L.push('');
  const fieldType = (f) => {
    const t = cppT(model, f.type.name);
    if (f.type.list) return `std::vector<${t}>`;
    if (f.optional) return `std::optional<${t}>`;
    return t;
  };
  for (const n of order) {
    if (model.structs.has(n)) {
      const s = model.structs.get(n);
      L.push(`struct ${n} {`);
      for (const f of s.fields) {
        const d = !f.type.list && !f.optional ? cppDefault(model, f.type.name) : '';
        L.push(`  ${fieldType(f)} ${cppIdent(f.name)}${d};`);
      }
      L.push(`  bool operator==(const ${n}&) const = default;`);
      L.push('};');
    } else {
      const u = model.unions.get(n);
      const vs = u.variants;
      L.push(`struct ${n} {`);
      L.push('  enum class Kind : std::uint32_t {');
      for (const v of vs) L.push(`    ${cppIdent(v.name)} = ${v.num},`);
      L.push('  };');
      L.push(`  std::variant<${vs.map((v) => (v.type === 'void' ? 'std::monostate' : cppT(model, v.type))).join(', ')}> v;`);
      L.push(`  [[nodiscard]] Kind kind() const noexcept;`);
      L.push(`  bool operator==(const ${n}&) const = default;`);
      L.push('};');
    }
    L.push('');
  }
  for (const n of order) {
    L.push(`void encode(wire::Writer& w, const ${n}& v);`);
    L.push(`[[nodiscard]] wire::Status decode(wire::Reader& r, ${n}& out);`);
  }
  L.push('');
  L.push('/// Decode `bytes` as the message type named `type`, re-encode it into `out`.');
  L.push('/// Used by the cross-language round-trip test; unknown names return bad_type.');
  L.push('[[nodiscard]] wire::Status roundtrip_by_name(std::string_view type, std::span<const std::uint8_t> bytes, std::vector<std::uint8_t>& out);');
  L.push('');
  L.push('/// Every message type name, for tests and fuzzers.');
  L.push('[[nodiscard]] std::span<const std::string_view> message_type_names() noexcept;');
  L.push('');
  L.push('}  // namespace premation::api');
  L.push('');
  L.push('#endif  // PREMATION_PROTOCOL_ENGINE_API_HPP');
  return L.join('\n') + '\n';
}

function genCppSource(model) {
  const L = [];
  L.push(`// ${HEADER_NOTE}`);
  L.push('');
  L.push('#include "engine_api.hpp"');
  L.push('');
  L.push('#include <array>');
  L.push('#include <utility>');
  L.push('');
  L.push('namespace premation::api {');
  L.push('');
  L.push('using wire::Status;');
  L.push('');
  for (const e of model.enums.values()) {
    L.push(`std::string_view to_string(${e.name} v) noexcept {`);
    L.push('  switch (v) {');
    for (const m of e.members) L.push(`    case ${e.name}::${cppIdent(m.name)}: return "${m.name}";`);
    L.push('  }');
    L.push('  return {};');
    L.push('}');
    L.push(`bool from_u32(std::uint32_t n, ${e.name}& out) noexcept {`);
    L.push('  switch (n) {');
    for (const m of e.members) L.push(`    case ${m.num}: out = ${e.name}::${cppIdent(m.name)}; return true;`);
    L.push('    default: return false;');
    L.push('  }');
    L.push('}');
  }
  L.push('');
  const order = cppOrder(model);

  const writeKey = (key) => `w.varint(${key}U);`;
  const writeScalar = (cat, t, expr) => {
    const b = base(model, t);
    switch (cat) {
      case 'bool': return `w.boolean(${expr});`;
      case 'varint': return `w.varint(${expr});`;
      case 'svarint': return `w.svarint(${expr});`;
      case 'enum': return `w.varint(static_cast<std::uint32_t>(${expr}));`;
      case 'f32': return `w.f32(${expr});`;
      case 'f64': return `w.f64(${expr});`;
      case 'string': return `w.str(${expr});`;
      case 'bytes': return `w.bytes(${expr});`;
    }
    throw new Error(cat + b);
  };
  const writeValue = (t, expr) => {
    const cat = category(model, t);
    if (cat === 'struct' || cat === 'union') return `{ const std::size_t s = w.begin_ld(); encode(w, ${expr}); w.end_ld(s); }`;
    return writeScalar(cat, t, expr);
  };
  /** Statement(s) that read one value into lvalue `dst`; return Status on failure. */
  const readInto = (t, dst) => {
    const cat = category(model, t);
    const b = base(model, t);
    switch (cat) {
      case 'bool': return `if (!r.boolean(${dst})) return Status::truncated;`;
      case 'varint': return b === 'u32' ? `if (!r.u32(${dst})) return Status::bad_value;` : `if (!r.varint(${dst})) return Status::truncated;`;
      case 'svarint': return b === 'i32' ? `if (!r.i32(${dst})) return Status::bad_value;` : `if (!r.svarint(${dst})) return Status::truncated;`;
      case 'enum': return `{ std::uint32_t n = 0; if (!r.u32(n)) return Status::bad_value; if (!from_u32(n, ${dst})) return Status::bad_enum; }`;
      case 'f32': return `if (!r.f32(${dst})) return Status::truncated;`;
      case 'f64': return `if (!r.f64(${dst})) return Status::truncated;`;
      case 'string': return `if (!r.str(${dst})) return Status::truncated;`;
      case 'bytes': return `if (!r.bytes(${dst})) return Status::truncated;`;
      case 'struct':
      case 'union':
        return `{ wire::Reader sub; if (!r.ld(sub)) return Status::truncated; if (const Status st = decode(sub, ${dst}); st != Status::ok) return st; }`;
    }
    throw new Error(cat);
  };

  for (const n of order) {
    if (model.structs.has(n)) {
      const s = model.structs.get(n);
      const fs = sortedFields(s);
      L.push(`void encode(wire::Writer& w, const ${n}& v) {`);
      if (fs.length === 0) L.push('  (void)w;', '  (void)v;');
      for (const f of fs) {
        const cat = category(model, f.type.name);
        const acc = `v.${cppIdent(f.name)}`;
        if (f.type.list) {
          if (isPackable(cat)) {
            const key = keyOf(f.num, cat, true);
            if (cat === 'bool') {
              L.push(`  if (!${acc}.empty()) { ${writeKey(key)} const std::size_t s = w.begin_ld(); for (const bool e : ${acc}) w.boolean(e); w.end_ld(s); }`);
            } else {
              L.push(`  if (!${acc}.empty()) { ${writeKey(key)} const std::size_t s = w.begin_ld(); for (const auto& e : ${acc}) ${writeScalar(cat, f.type.name, 'e')} w.end_ld(s); }`);
            }
          } else {
            const key = keyOf(f.num, cat, false);
            L.push(`  for (const auto& e : ${acc}) { ${writeKey(key)} ${writeValue(f.type.name, 'e')} }`);
          }
        } else {
          const key = keyOf(f.num, cat, false);
          if (f.optional) L.push(`  if (${acc}.has_value()) { ${writeKey(key)} ${writeValue(f.type.name, `*${acc}`)} }`);
          else L.push(`  ${writeKey(key)} ${writeValue(f.type.name, acc)}`);
        }
      }
      L.push('}');
      L.push('');
      L.push(`Status decode(wire::Reader& r, ${n}& out) {`);
      const req = fs.filter((f) => !f.type.list && !f.optional);
      if (fs.length === 0) L.push('  (void)out;');
      for (const f of req) L.push(`  bool has_${cppIdent(f.name)} = false;`);
      L.push('  while (!r.at_end()) {');
      L.push('    std::uint64_t key = 0;');
      L.push('    if (!r.varint(key)) return Status::truncated;');
      L.push('    switch (key) {');
      for (const f of fs) {
        const cat = category(model, f.type.name);
        const acc = `out.${cppIdent(f.name)}`;
        const elemT = cppT(model, f.type.name);
        if (f.type.list) {
          if (isPackable(cat)) {
            L.push(`      case ${keyOf(f.num, cat, true)}U: {`);
            L.push('        wire::Reader sub;');
            L.push('        if (!r.ld(sub)) return Status::truncated;');
            L.push(`        while (!sub.at_end()) { ${elemT} e${cppDefault(model, f.type.name)}; ${readInto(f.type.name, 'e').replace(/\br\./g, 'sub.')} ${acc}.push_back(e); }`);
            L.push('        break;');
            L.push('      }');
          } else {
            L.push(`      case ${keyOf(f.num, cat, false)}U: {`);
            // Decode in place: no temporary + move per element (the output is discarded on any error).
            L.push(`        auto& e = ${acc}.emplace_back();`);
            L.push(`        ${readInto(f.type.name, 'e')}`);
            L.push('        break;');
            L.push('      }');
          }
        } else if (f.optional) {
          L.push(`      case ${keyOf(f.num, cat, false)}U: {`);
          L.push(`        ${elemT} e${cppDefault(model, f.type.name)};`);
          L.push(`        ${readInto(f.type.name, 'e')}`);
          L.push(`        ${acc} = std::move(e);`);
          L.push('        break;');
          L.push('      }');
        } else {
          L.push(`      case ${keyOf(f.num, cat, false)}U: {`);
          L.push(`        ${readInto(f.type.name, acc)}`);
          L.push(`        has_${cppIdent(f.name)} = true;`);
          L.push('        break;');
          L.push('      }');
        }
      }
      L.push('      default:');
      L.push('        if (!r.skip(key)) return Status::truncated;');
      L.push('        break;');
      L.push('    }');
      L.push('  }');
      for (const f of req) L.push(`  if (!has_${cppIdent(f.name)}) return Status::missing_field;`);
      L.push('  return Status::ok;');
      L.push('}');
      L.push('');
    } else {
      const u = model.unions.get(n);
      const vs = u.variants;
      L.push(`${n}::Kind ${n}::kind() const noexcept {`);
      L.push(`  static constexpr std::array<Kind, ${vs.length}> kKinds = {${vs.map((v) => `Kind::${cppIdent(v.name)}`).join(', ')}};`);
      L.push('  return kKinds[v.index()];');
      L.push('}');
      L.push('');
      L.push(`void encode(wire::Writer& w, const ${n}& v) {`);
      L.push('  switch (v.v.index()) {');
      vs.forEach((x, i) => {
        if (x.type === 'void') { L.push(`    case ${i}: w.varint(${x.num * 8 + 2}U); w.varint(0U); return;`); return; }
        const cat = category(model, x.type);
        L.push(`    case ${i}: ${writeKey(keyOf(x.num, cat, false))} ${writeValue(x.type, `std::get<${i}>(v.v)`)} return;`);
      });
      L.push('    default: return;');
      L.push('  }');
      L.push('}');
      L.push('');
      L.push(`Status decode(wire::Reader& r, ${n}& out) {`);
      L.push('  bool seen = false;');
      L.push('  while (!r.at_end()) {');
      L.push('    std::uint64_t key = 0;');
      L.push('    if (!r.varint(key)) return Status::truncated;');
      L.push('    switch (key) {');
      vs.forEach((x, i) => {
        if (x.type === 'void') {
          L.push(`      case ${x.num * 8 + 2}U: {`);
          L.push('        if (seen) return Status::multiple_variants;');
          L.push('        wire::Reader sub;');
          L.push('        if (!r.ld(sub)) return Status::truncated;');
          L.push(`        out.v.emplace<${i}>();`);
          L.push('        seen = true;');
          L.push('        break;');
          L.push('      }');
          return;
        }
        const cat = category(model, x.type);
        L.push(`      case ${keyOf(x.num, cat, false)}U: {`);
        L.push('        if (seen) return Status::multiple_variants;');
        L.push(`        ${cppT(model, x.type)} e${cppDefault(model, x.type)};`);
        L.push(`        ${readInto(x.type, 'e')}`);
        L.push(`        out.v.emplace<${i}>(std::move(e));`);
        L.push('        seen = true;');
        L.push('        break;');
        L.push('      }');
      });
      L.push('      default:');
      L.push('        if (!r.skip(key)) return Status::truncated;');
      L.push('        break;');
      L.push('    }');
      L.push('  }');
      L.push('  return seen ? Status::ok : Status::unknown_variant;');
      L.push('}');
      L.push('');
    }
  }

  const names = messageTypes(model);
  L.push('namespace {');
  L.push('template <class M>');
  L.push('Status roundtrip(std::span<const std::uint8_t> bytes, std::vector<std::uint8_t>& out) {');
  L.push('  M m{};');
  L.push('  wire::Reader r(bytes);');
  L.push('  if (const Status st = decode(r, m); st != Status::ok) return st;');
  L.push('  wire::Writer w;');
  L.push('  encode(w, m);');
  L.push('  out = w.take();');
  L.push('  return Status::ok;');
  L.push('}');
  L.push(`constexpr std::array<std::string_view, ${names.length}> kNames = {`);
  for (const n of names) L.push(`    "${n}",`);
  L.push('};');
  L.push('}  // namespace');
  L.push('');
  L.push('std::span<const std::string_view> message_type_names() noexcept { return kNames; }');
  L.push('');
  L.push('Status roundtrip_by_name(std::string_view type, std::span<const std::uint8_t> bytes, std::vector<std::uint8_t>& out) {');
  for (const n of names) L.push(`  if (type == "${n}") return roundtrip<${n}>(bytes, out);`);
  L.push('  return Status::bad_type;');
  L.push('}');
  L.push('');
  L.push('}  // namespace premation::api');
  return L.join('\n') + '\n';
}

function genFixtures(model) {
  const reflect = makeReflect(model);
  const sampler = makeSampler(model);
  const L = [];
  L.push(`// ${HEADER_NOTE}`);
  L.push('//');
  L.push('// One canonical encoding per sample value of every message type, produced by');
  L.push('// the generator\'s reflective encoder. The TypeScript test proves the generated');
  L.push('// TS codec emits these same bytes; native/protocol/tests proves the C++ codec');
  L.push('// decodes and re-encodes each to the identical bytes.');
  L.push('// Entry: { type name, sample label, bytes }.');
  L.push('');
  let count = 0;
  for (const n of messageTypes(model)) {
    for (const s of sampler.samplesFor(n)) {
      const b = reflect.encode(n, s.value);
      const hex = [];
      for (let i = 0; i < b.length; i++) hex.push(`0x${b[i].toString(16).padStart(2, '0')}`);
      L.push(`PREMATION_FIXTURE("${n}", "${s.label}", ${hex.length ? hex.join(',') : ''})`);
      count++;
    }
  }
  L.push(`// ${count} fixtures`);
  return L.join('\n') + '\n';
}

// ─────────────────────────────────────────────────────────────────────────────
// Driver
// ─────────────────────────────────────────────────────────────────────────────

function loadSchema(dir = SCHEMA_DIR) {
  const files = readdirSync(dir)
    .filter((f) => f.endsWith('.eapi'))
    .sort()
    .map((f) => ({ name: `schema/${f}`, src: readFileSync(join(dir, f), 'utf8') }));
  if (files.length === 0) throw new Error(`no .eapi files in ${dir}`);
  return parse(files);
}

/** Every generated file: absolute path → contents. */
function generateAll(model = loadSchema()) {
  return {
    [join(TS_OUT, 'types.ts')]: genTsTypes(model),
    [join(TS_OUT, 'codec.ts')]: genTsCodec(model),
    [join(TS_OUT, 'meta.ts')]: genTsMeta(model),
    [join(CPP_OUT, 'engine_api.hpp')]: genCppHeader(model),
    [join(CPP_OUT, 'engine_api.cpp')]: genCppSource(model),
    [join(CPP_OUT, 'fixtures.inc')]: genFixtures(model),
    // Electron main speaks the frame channel (schema 95_frames.eapi) itself.
    [join(ELECTRON_OUT, 'engineWire.ts')]: genTsWireCopy(),
    [join(ELECTRON_OUT, 'frameChannel.ts')]: genTsFamilyModule(model, 'FrameChannel', './engineWire'),
  };
}

/** Normalise line endings so a CRLF checkout does not read as stale. */
function sameText(a, b) { return a.replace(/\r\n/g, '\n') === b.replace(/\r\n/g, '\n'); }

function staleFiles(model) {
  const out = [];
  for (const [path, text] of Object.entries(generateAll(model))) {
    if (!existsSync(path) || !sameText(readFileSync(path, 'utf8'), text)) out.push(relative(ROOT, path).replace(/\\/g, '/'));
  }
  return out;
}

module.exports = {
  parse,
  loadSchema,
  generateAll,
  staleFiles,
  makeReflect,
  makeSampler,
  messageTypes,
  category,
  base,
};

if (require.main === module) {
  const check = process.argv.includes('--check');
  const model = loadSchema();
  if (check) {
    const stale = staleFiles(model);
    if (stale.length) {
      console.error(`engine-api: generated files are stale — run \`npm run engine-api:gen\`:\n  ${stale.join('\n  ')}`);
      process.exit(1);
    }
    console.log('engine-api: generated files are up to date.');
  } else {
    for (const [path, text] of Object.entries(generateAll(model))) {
      mkdirSync(dirname(path), { recursive: true });
      writeFileSync(path, text);
      console.log(`wrote ${relative(ROOT, path).replace(/\\/g, '/')}`);
    }
    console.log(`engine-api v${model.version.major}.${model.version.minor}: ${model.commands.length} commands, ${model.queries.length} queries, ${model.events.length} events, ${model.structs.size} structs, ${model.unions.size} unions, ${model.enums.size} enums.`);
  }
}
