/**
 * Cross-engine CJK paragraph wrapping parity (plan D2w). The C++ scene builder
 * wraps a paragraph with an ideographic character the way `wrapText` does —
 * `wrapUnits` with a first-line indent, `joinWrapped` inserting its breaks —
 * then reads the soft breaks back (`softBreakLines`) and moves the runs onto
 * the wrapped text (`alignIndicesToWrap` → `insertedBreakIndices` +
 * `shiftSpansForInsertedBreaks`). This test runs those over deterministic
 * advances (no fonts: widths are the caller's) and records them in
 * `native/engine/tests/data/cjk_wrap_parity.json`, which
 * `native/engine/tests/test_raster_text_core.cpp` (the line-break half) and
 * `native/engine/tests/test_text_port_parity.cpp` (the soft breaks) replay.
 *
 * Without Intl.Segmenter (the rows are CJK, kana, hangul and spaced Latin,
 * where the word joins add nothing), so the C++ need not load ICU.
 *
 * `GEN_NATIVE_CJKWRAP=1 npx jest cjkWrapCrossEngine` rewrites the fixture.
 */

import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { splitGraphemes } from './graphemes';
import { insertedBreakIndices, joinWrapped, setWordSegmenterForTest, shiftSpansForInsertedBreaks, wrapUnits } from './lineBreak';
import { softBreakLines } from './textExtras';

const OUT = path.resolve(__dirname, '../../../native/engine/tests/data/cjk_wrap_parity.json');

/** Paragraph texts ('\n' = hard breaks between paragraphs). */
const TEXTS: string[] = [
  '日本語の文章、「引用」とカタカナ。ひらがなー',
  '中文句子没有空格English混排。第二句话也很长很长很长。',
  '한국어 문장은 띄어쓰기를 합니다 그리고 계속됩니다',
  '東京タワー（とうきょうタワー）は、東京都港区芝公園にある総合電波塔である。',
  'ｶﾀｶﾅとぁぃぅぇぉっゃゅょ小書き、句読点。。。',
  'Latin words then 漢字が続く文章 and back to Latin words',
  '一行目の段落です。\n二行目の段落は少し長めに書いてあります。\n三',
  '「括弧」『二重括弧』【隅付き】〔亀甲〕（全角）',
  '価格は＄１００、€２０、￥３０００です。',
  '長い長い長い長い長い長い長い長い長い長い長い長い長い長い',
  'short',
  '',
];

interface Row {
  text: string;
  /** Per paragraph: the grapheme advances, the limit and the first-line indent. */
  paragraphs: Array<{ units: string[]; lengths: number[]; limit: number; firstLineIndent: number; starts: number[]; joined: string }>;
  wrapped: string;
  softBreakLines: number[];
  inserted: number[];
  runs: Array<{ start: number; end: number }>;
  shifted: Array<{ start: number; end: number }>;
}

function generate(): { rows: Row[] } {
  setWordSegmenterForTest(true);
  try {
    const rows: Row[] = TEXTS.map((text, t) => {
      const paragraphs = text.split('\n').map((p, k) => {
        const units = [...splitGraphemes(p)];
        // Deterministic advances: ideographs wider than Latin, varied by position.
        const lengths = units.map((u, i) => (u.charCodeAt(0) > 0x2e7f ? 14 : 7) + ((i * 5 + t + k) % 3));
        const limit = 60 + ((t + k) % 4) * 23;
        const firstLineIndent = (t + k) % 3 === 0 ? 0 : ((t + k) % 3) * 9 - 6;
        const starts = wrapUnits(units, lengths, (line) => limit - (line === 0 ? firstLineIndent : 0));
        return { units, lengths, limit, firstLineIndent, starts, joined: joinWrapped(units, starts) };
      });
      const wrapped = paragraphs.map((p) => p.joined).join('\n');
      const rawClusters = [...splitGraphemes(text)];
      const n = rawClusters.length;
      const runs = n === 0 ? [] : [{ start: 0, end: Math.min(3, n) }, { start: Math.floor(n / 3), end: Math.floor((2 * n) / 3) }, { start: Math.max(0, n - 2), end: n }];
      const inserted = insertedBreakIndices(rawClusters, [...splitGraphemes(wrapped)]);
      return {
        text,
        paragraphs,
        wrapped,
        softBreakLines: softBreakLines(text, wrapped),
        inserted,
        runs,
        shifted: shiftSpansForInsertedBreaks(runs, inserted),
      };
    });
    return { rows };
  } finally {
    setWordSegmenterForTest(false);
  }
}

test('the C++ CJK wrap parity fixture matches lineBreak.ts + textExtras.softBreakLines', () => {
  const fixture = generate();
  // Something must insert a break, or the fixture tests only the space path.
  expect(fixture.rows.some((r) => r.inserted.length > 0)).toBe(true);
  const text = `${JSON.stringify({ comment: 'Generated by src/core/text/cjkWrapCrossEngine.test.ts (GEN_NATIVE_CJKWRAP=1). Do not edit.', ...fixture }, null, 1)}\n`;
  if (process.env.GEN_NATIVE_CJKWRAP === '1') {
    writeFileSync(OUT, text);
    return;
  }
  expect(existsSync(OUT)).toBe(true);
  expect(JSON.parse(readFileSync(OUT, 'utf8'))).toEqual(JSON.parse(text));
});
