/**
 * Cross-engine line-break parity (plan E3). `native/engine/src/raster/line_break.cpp`
 * ports lineBreak.ts, and its word joins come from ICU's word break iterator
 * (word_break_ffi.cpp) as `Intl.Segmenter` does here. This test runs the TS
 * `breakOpportunities` / `wrapUnits` over a spread of scripts — the dictionary
 * scripts (Thai, Lao, Khmer, Myanmar) the joins exist for, script changes,
 * CJK, bidi scripts, numbers, emoji — with and without the segmenter, and
 * records them in `native/engine/tests/data/line_break_parity.json`, which
 * `native/engine/tests/test_raster_text_core.cpp` replays against the C++.
 *
 * `GEN_NATIVE_LINE_BREAKS=1 npx jest lineBreakCrossEngine` rewrites the
 * fixture; without it this test fails when the fixture is stale.
 */

import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { splitGraphemes } from './graphemes';
import { breakOpportunities, setWordSegmenterForTest, wrapUnits } from './lineBreak';

const OUT = path.resolve(__dirname, '../../../native/engine/tests/data/line_break_parity.json');

const TEXTS: string[] = [
  'The quick brown fox jumps over the lazy dog.',
  "can't won't 3.14 1,000 e-mail a/b a_b x:y",
  'ภาษาไทยเป็นภาษาที่ไม่มีการเว้นวรรคระหว่างคำ',
  'สวัสดีครับ ยินดีต้อนรับสู่ประเทศไทย',
  'ພາສາລາວເປັນພາສາທີ່ສວຍງາມ',
  'ភាសាខ្មែរគឺជាភាសាផ្លូវការ',
  'မြန်မာဘာသာစကားသည်လှပသည်',
  'Hello世界, こんにちはWorld',
  'abcภาษาไทยdef 123ไทย',
  '日本語の文章、「引用」とカタカナ。ひらがなー',
  '한국어 문장은 띄어쓰기를 합니다',
  'مرحبا بالعالم العربي',
  'שלום עולם עברית',
  'हिन्दी भाषा सुंदर है',
  'Русский текст с дефисом—тире и-так-далее',
  'emoji 👍🏽 family 👨‍👩‍👧 flags 🇯🇵🇺🇸 ok',
  'mixed ΑΒΓ abc Δέλτα',
  'naïve café résumé',
  'tab\tseparated\tvalues',
  '中文句子没有空格English混排。',
  'ไทย日本語English',
  'x',
  '',
];

interface Row {
  text: string;
  units: string[];
  segments: Array<[number, boolean]>;
  withSegmenter: number[];
  withoutSegmenter: number[];
  wrap: { lengths: number[]; limit: number; starts: number[] };
}

const trueIdx = (b: boolean[]): number[] => b.flatMap((v, i) => (v ? [i] : []));

function generate(): { icu: string; rows: Row[] } {
  const seg = new Intl.Segmenter(undefined, { granularity: 'word' });
  const rows: Row[] = TEXTS.map((text, t) => {
    const units = [...splitGraphemes(text)];
    setWordSegmenterForTest(false);
    const withSegmenter = trueIdx(breakOpportunities(units));
    // Deterministic lengths: a few px per unit, varied by position.
    const lengths = units.map((_, i) => 6 + ((i * 7 + t) % 5));
    const limit = 40 + (t % 3) * 17;
    const starts = wrapUnits(units, lengths, limit);
    setWordSegmenterForTest(true);
    const withoutSegmenter = trueIdx(breakOpportunities(units));
    setWordSegmenterForTest(false);
    const segments: Array<[number, boolean]> = [...seg.segment(units.join(''))].map((s) => [s.index, s.isWordLike === true]);
    return { text, units, segments, withSegmenter, withoutSegmenter, wrap: { lengths, limit, starts } };
  });
  return { icu: process.versions.icu ?? '', rows };
}

test('the C++ line-break parity fixture matches lineBreak.ts', () => {
  const fixture = generate();
  // The segmenter must matter somewhere, or the fixture tests nothing.
  expect(fixture.rows.some((r) => r.withSegmenter.join() !== r.withoutSegmenter.join())).toBe(true);
  const text = `${JSON.stringify({ comment: 'Generated by src/core/text/lineBreakCrossEngine.test.ts (GEN_NATIVE_LINE_BREAKS=1). Do not edit.', ...fixture }, null, 1)}\n`;
  if (process.env.GEN_NATIVE_LINE_BREAKS === '1') {
    writeFileSync(OUT, text);
    return;
  }
  expect(existsSync(OUT)).toBe(true);
  const stored = JSON.parse(readFileSync(OUT, 'utf8')) as { icu: string; rows: Row[] };
  if (stored.icu === fixture.icu) {
    expect(stored).toEqual(JSON.parse(text));
    return;
  }
  // Another ICU splits graphemes and dictionary words differently, so only the
  // ICU-free logic is comparable: breaks with the segmenter off, over the stored units.
  setWordSegmenterForTest(true);
  try {
    expect(stored.rows.map((r) => trueIdx(breakOpportunities(r.units)))).toEqual(stored.rows.map((r) => r.withoutSegmenter));
  } finally {
    setWordSegmenterForTest(false);
  }
});
