/**
 * Cross-engine Corner Pin parity (plan D2w 3D leftovers: corner pin on 3D
 * layers — and on every other layer, since the pin is one render stage).
 *
 * For a spread of stored pins the fixture records `readNodeCornerPin` (the
 * snapshot side: identity / non-convex / malformed pins read as none) and, for
 * the usable ones, what snapshotToFrameScene's `resolveCornerPin` produces for
 * a few affine layer models: the homography (`squareToQuad`, float32), the
 * projective render model (`Mat3.multiply(model, pin)`) and the pinned bounds.
 * The C++ port (`native/engine/src/scene/corner_pin.cpp`,
 * tests/test_corner_pin_parity.cpp) must match float for float.
 *
 * `GEN_NATIVE_PIN=1 npx jest cornerPinCrossEngine` rewrites the fixture.
 */

import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { Mat3, squareToQuad, type Quad } from '@motion/renderer';
import type { SceneNode } from '@core/types';
import { readNodeCornerPin } from './cornerPin';

const OUT = path.resolve(__dirname, '../../../native/engine/tests/data/corner_pin_parity.json');

const PINS: unknown[] = [
  [0, 0, 1, 0, 1, 1, 0, 1], // identity → none
  [0, 0, 1, 0, 1, 1, 0, 1.0000005], // within the identity epsilon → none
  [0.1, 0.05, 0.93, 0.12, 0.88, 0.97, 0.02, 0.9], // a perspective pin
  [0.2, 0, 1.2, 0, 1, 1, 0, 1], // a parallelogram → affine homography
  [0, 0, 1, 0, 0.2, 0.2, 0, 1], // non-convex (reflex corner) → none
  [0, 0, 1, 0, 1, 0, 0, 0], // degenerate → none
  [0, 0, 1, 0, 1, 1, 0], // malformed length → none
  [0, 0, 1, 'x', 1, 1, 0, 1], // non-number → none
  [-0.3, -0.1, 1.4, 0.2, 1.1, 1.3, -0.2, 0.8], // outside the unit square, still convex
  [0.5, 0, 1, 0.5, 0.5, 1, 0, 0.5], // a diamond
];

/** Affine layer models (column-major float32): identity, a placed quad, a rotated + scaled one. */
const MODELS: number[][] = [
  [1, 0, 0, 0, 1, 0, 0, 0, 1],
  [320, 0, 0, 0, 180, 0, 40.5, 60.25, 1],
  Array.from(Mat3.multiply(Mat3.compose(250, 140, 0.4, 300, 200), Mat3.translation(-0.5, -0.5))),
];

function node(pin: unknown): SceneNode {
  return { id: 'n', name: 'n', parent: null, children: [], visible: true, locked: false, components: [{ id: 'n_fx', type: 'fx', props: { cornerPin: pin } }] } as unknown as SceneNode;
}

function generate() {
  return PINS.map((pin) => {
    const read = readNodeCornerPin(node(pin));
    if (!read) return { pin, read: null };
    const quad: Quad = [
      { x: read[0], y: read[1] }, { x: read[2], y: read[3] }, { x: read[4], y: read[5] }, { x: read[6], y: read[7] },
    ];
    const h = squareToQuad(quad);
    const resolved = MODELS.map((mv) => {
      const model = Mat3.create();
      mv.forEach((v, i) => { model[i] = v; });
      if (!h) return null;
      const renderModel = Mat3.multiply(model, h);
      let minX = Infinity, minY = Infinity, maxX = -Infinity, maxY = -Infinity;
      for (const c of quad) {
        const w = Mat3.transformPoint(model, c);
        minX = Math.min(minX, w.x); minY = Math.min(minY, w.y);
        maxX = Math.max(maxX, w.x); maxY = Math.max(maxY, w.y);
      }
      return { model: Array.from(model), renderModel: Array.from(renderModel), bounds: [minX, minY, maxX - minX, maxY - minY] };
    });
    return { pin, read: [...read], homography: h ? Array.from(h) : null, resolved };
  });
}

test('the C++ corner pin parity fixture matches readNodeCornerPin + resolveCornerPin', () => {
  const rows = generate();
  const text = `${JSON.stringify({ comment: 'Generated by src/core/scene/cornerPinCrossEngine.test.ts (GEN_NATIVE_PIN=1). Do not edit.', rows })}\n`;
  if (process.env.GEN_NATIVE_PIN === '1') {
    writeFileSync(OUT, text);
    return;
  }
  expect(existsSync(OUT)).toBe(true);
  expect((JSON.parse(readFileSync(OUT, 'utf8')) as { rows: unknown[] }).rows).toEqual(rows);
  expect(rows.filter((r) => r.read !== null).length).toBeGreaterThanOrEqual(4);
});
