/**
 * Cross-engine image-sky parity (plan D2w 3D leftovers): an environment light
 * whose sky is `asset:<id>` — an imported equirect image. For a few decoded
 * RGBA8 images (generated from a formula the C++ test repeats) the fixture
 * records what environmentImage.ts derives from the pixels: the resampled
 * linear equirect (`resampleEquirect`, as FNV-1a 64 of its float bytes), the
 * SH9 projection (`shProjectEquirect`), the derived rig (`environmentRig`) and
 * the prefiltered reflection atlas (`buildEnvSpecularAtlas` under
 * `envAtlasKey('asset:<id>#<hashEnvPixels>')`).
 *
 * The C++ port (`native/engine/src/scene/env_light.cpp` + `env_asset.cpp`,
 * tests/test_env_asset_parity.cpp) must match byte for byte.
 *
 * `GEN_NATIVE_ENV=1 npx jest envAssetCrossEngine` rewrites the fixture.
 */

import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import {
  ENV_SPEC_HEIGHT, ENV_SPEC_LEVELS, ENV_SPEC_WIDTH, buildEnvSpecularAtlas, environmentRig, resampleEquirect, shProjectEquirect,
} from './environmentLight';
import { envAtlasKey, hashEnvPixels } from './envAtlasCache';

const OUT = path.resolve(__dirname, '../../../native/engine/tests/data/env_asset_parity.json');

function fnv1a64(view: ArrayBufferView): string {
  const bytes = new Uint8Array(view.buffer, view.byteOffset, view.byteLength);
  let h = 0xcbf29ce484222325n;
  for (const b of bytes) {
    h ^= BigInt(b);
    h = (h * 0x100000001b3n) & 0xffffffffffffffffn;
  }
  return h.toString(16).padStart(16, '0');
}

/** The decoded image (getImageData: straight RGBA8, opaque). Repeated in the C++ test. */
function image(w: number, h: number, seed: number): Uint8ClampedArray {
  const px = new Uint8ClampedArray(w * h * 4);
  for (let y = 0; y < h; y++) {
    for (let x = 0; x < w; x++) {
      const o = (y * w + x) * 4;
      px[o] = (x * 7 + y * 3 + seed) & 255;
      px[o + 1] = (x * x + y * 5 + seed * 3) & 255;
      px[o + 2] = ((x ^ y) * 11 + seed * 7) & 255;
      px[o + 3] = 255;
    }
  }
  return px;
}

const CASES = [
  { name: 'hdri-300x150', w: 300, h: 150, seed: 1 },
  { name: 'small-100x40', w: 100, h: 40, seed: 2 },
  { name: 'exact-512x256', w: 512, h: 256, seed: 3 },
];

function generate() {
  return CASES.map((c) => {
    const px = image(c.w, c.h, c.seed);
    const base = resampleEquirect(px, c.w, c.h, ENV_SPEC_WIDTH, ENV_SPEC_HEIGHT, { isLinear: false });
    const sh = shProjectEquirect(px, c.w, c.h, { isLinear: false });
    const rig = environmentRig(sh, 80, 30).map((l) => ({ kind: l.kind, color: l.color, intensity: l.intensity, from: l.from ? [l.from.x, l.from.y, l.from.z] : null }));
    const id = envAtlasKey(`asset:${c.name}#${hashEnvPixels(base)}`, ENV_SPEC_WIDTH, ENV_SPEC_HEIGHT, ENV_SPEC_LEVELS);
    const atlas = buildEnvSpecularAtlas(base, id);
    return {
      ...c,
      resampled: { width: base.width, height: base.height, fnv: fnv1a64(base.data) },
      sh: Array.from(sh),
      rig,
      atlas: { id: atlas.id, width: atlas.width, height: atlas.height, levels: atlas.levels, scale: atlas.scale, fnv: fnv1a64(atlas.data) },
    };
  });
}

test('the C++ image-sky parity fixture matches environmentLight.ts', () => {
  const rows = generate();
  const text = `${JSON.stringify({ comment: 'Generated by src/core/scene/envAssetCrossEngine.test.ts (GEN_NATIVE_ENV=1). Do not edit.', rows })}\n`;
  if (process.env.GEN_NATIVE_ENV === '1') {
    writeFileSync(OUT, text);
    return;
  }
  expect(existsSync(OUT)).toBe(true);
  expect((JSON.parse(readFileSync(OUT, 'utf8')) as { rows: unknown[] }).rows).toEqual(rows);
});
