/**
 * Cross-engine parity of the extrusion FALLBACK geometry (plan D2w 3D
 * leftovers: the geometric faces an extruded rect / ellipse is drawn with when
 * the mesh path is blocked): `extrusionGeometry` + `clampBevel`. The C++ port
 * (`native/engine/src/scene/extrusion_faces.cpp`,
 * tests/test_extrusion_faces_parity.cpp) must give the same faces — order,
 * suffix, size and every matrix element — and the same emitted bevel.
 *
 * `GEN_NATIVE_EXTFACES=1 npx jest extrusionFacesCrossEngine` rewrites the fixture.
 */

import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { clampBevel, extrusionGeometry, type ExtrusionOptions } from './extrusion';
import { faceKindOf } from './faceMaterials';

const OUT = path.resolve(__dirname, '../../../native/engine/tests/data/extrusion_faces_parity.json');

interface Case { w: number; h: number; d: number; shape: 'rect' | 'ellipse'; segments?: number; opts?: ExtrusionOptions }

const CASES: Case[] = [
  { w: 320, h: 180, d: 40, shape: 'rect' },
  { w: 320, h: 180, d: 40, shape: 'rect', opts: { bevel: 6 } },
  { w: 100, h: 60, d: 10, shape: 'rect', opts: { bevel: 80 } }, // clamped to d/2: no walls left
  { w: 40, h: 40, d: 300, shape: 'rect', opts: { bevel: 20 } }, // clamped to w/2: no back cap
  { w: 320, h: 180, d: 40, shape: 'rect', opts: { cornerRadius: 24, bevel: 12 } }, // rounded: bevel ignored
  { w: 200, h: 90, d: 25, shape: 'rect', opts: { cornerRadius: 500 } }, // radius clamps to h/2
  { w: 320, h: 180, d: 40, shape: 'rect', opts: { wallSegments: 20 } },
  { w: 320, h: 180, d: 40, shape: 'rect', opts: { wallSegments: 3.7, bevel: 5 } },
  { w: 240, h: 240, d: 55.5, shape: 'ellipse' },
  { w: 300, h: 120, d: 12, shape: 'ellipse', segments: 7, opts: { bevel: 9 } },
  { w: 300, h: 120, d: 12, shape: 'ellipse', segments: 1 },
  { w: 0, h: 120, d: 12, shape: 'rect' },
  { w: 10, h: 10, d: 0, shape: 'ellipse' },
];

const BEVELS: Array<[number, number, number, number]> = [
  [100, 50, 20, 5], [100, 50, 20, 40], [100, 50, 20, -1], [0, 50, 20, 5], [100, 50, 20, Number.NaN], [7, 9, 3, 100],
];

function generate() {
  const cases = CASES.map((c) => {
    const g = extrusionGeometry(c.w, c.h, c.d, c.shape, c.segments, c.opts);
    return {
      ...c,
      bevel: g.bevel,
      faces: g.faces.map((f) => ({ m: Array.from(f.m), w: f.w, h: f.h, role: f.role, suffix: f.suffix, kind: faceKindOf(f.role, f.suffix) })),
    };
  });
  // JSON has no NaN: a NaN request travels as null and is re-made NaN on the C++ side.
  const bevels = BEVELS.map(([w, h, d, b]) => ({ w, h, d, b: Number.isNaN(b) ? null : b, out: clampBevel(w, h, d, b) }));
  return { cases, bevels };
}

test('the C++ extrusion faces parity fixture matches extrusionGeometry + clampBevel', () => {
  const fixture = generate();
  const text = `${JSON.stringify({ comment: 'Generated by src/core/scene/extrusionFacesCrossEngine.test.ts (GEN_NATIVE_EXTFACES=1). Do not edit.', ...fixture })}\n`;
  if (process.env.GEN_NATIVE_EXTFACES === '1') {
    writeFileSync(OUT, text);
    return;
  }
  expect(existsSync(OUT)).toBe(true);
  expect(JSON.parse(readFileSync(OUT, 'utf8'))).toEqual(JSON.parse(text));
  expect(fixture.cases[1]!.bevel).toBe(6);
});
