/**
 * Cross-engine primitive parity (plan D2). For a spread of primitive specs —
 * every type, default and odd segment counts, fractional sizes, open tubes,
 * a vertex count past 16-bit indices — the fixture records the mesh the
 * editor's layer produces (`primitiveEntryFor`: key, interleaved vertices,
 * index width and bytes, the draw range's role). The C++ engine rebuilds each
 * FROM ITS KEY ALONE (`native/engine/src/scene/primitive_mesh.cpp`,
 * tests/test_primitive_parity.cpp) and must match byte for byte.
 *
 * `GEN_NATIVE_PRIMITIVES=1 npx jest primitiveCrossEngine` rewrites the fixture;
 * without it this test fails when the fixture is stale.
 */

import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import type { SceneNode } from '@core/types';
import { defaultPrimitiveSpec, makePrimitiveComponent, primitiveEntryFor, clearPrimitiveMeshCache, type PrimitiveSpec } from './primitiveLayer';

const OUT = path.resolve(__dirname, '../../../native/engine/tests/data/primitive_parity.json');

const SPECS: PrimitiveSpec[] = [
  defaultPrimitiveSpec('sphere'),
  { ...defaultPrimitiveSpec('sphere', 97.3), radialSegments: 7, heightSegments: 3 },
  defaultPrimitiveSpec('cylinder'),
  { ...defaultPrimitiveSpec('cylinder'), radiusTop: 40.25, capped: false, radialSegments: 5 },
  defaultPrimitiveSpec('cone'),
  { ...defaultPrimitiveSpec('cone', 180), capped: false },
  defaultPrimitiveSpec('torus'),
  { ...defaultPrimitiveSpec('torus', 300), tube: 12.5, radialSegments: 11, heightSegments: 4 },
  defaultPrimitiveSpec('capsule'),
  { ...defaultPrimitiveSpec('capsule', 150), height: 60 }, // shorter than two radii: a sphere
  defaultPrimitiveSpec('box'),
  { ...defaultPrimitiveSpec('box'), width: 12.345, height: 300, depth: 0.5 },
  // 257 × 256 vertices > 65535: 32-bit indices.
  { ...defaultPrimitiveSpec('sphere'), radialSegments: 256, heightSegments: 255 },
  // Segment counts the generators clamp (below the minimum, fractional).
  { ...defaultPrimitiveSpec('torus'), radialSegments: 1, heightSegments: 2.7 },
];

function node(spec: PrimitiveSpec): SceneNode {
  return { id: 'p', name: 'p', parent: null, children: [], visible: true, locked: false, components: [makePrimitiveComponent('p', spec)] } as unknown as SceneNode;
}

/**
 * The mesh as its exact bytes' FNV-1a 64 (hex) plus counts: the sign of every
 * zero and every float bit counts, and a 65k-vertex sphere stays a line.
 */
interface Row { key: string; vertexCount: number; indexCount: number; verticesFnv: string; indicesFnv: string; index32: boolean; role: 'front' | 'side' }

function fnv1a64(view: ArrayBufferView): string {
  const bytes = new Uint8Array(view.buffer, view.byteOffset, view.byteLength);
  let h = 0xcbf29ce484222325n;
  for (const b of bytes) {
    h ^= BigInt(b);
    h = (h * 0x100000001b3n) & 0xffffffffffffffffn;
  }
  return h.toString(16).padStart(16, '0');
}

function generate(): Row[] {
  clearPrimitiveMeshCache();
  return SPECS.map((spec) => {
    const e = primitiveEntryFor(node(spec))!;
    return {
      key: e.key,
      vertexCount: e.vertices.length / 8,
      indexCount: e.indices.length,
      verticesFnv: fnv1a64(e.vertices),
      indicesFnv: fnv1a64(e.indices),
      index32: e.indices instanceof Uint32Array,
      role: e.doubleSided ? 'front' : 'side',
    };
  });
}

test('the C++ primitive parity fixture matches primitiveEntryFor', () => {
  const rows = generate();
  const text = `${JSON.stringify({ comment: 'Generated by src/core/scene/primitiveCrossEngine.test.ts (GEN_NATIVE_PRIMITIVES=1). Do not edit.', rows })}\n`;
  if (process.env.GEN_NATIVE_PRIMITIVES === '1') {
    writeFileSync(OUT, text);
    return;
  }
  expect(existsSync(OUT)).toBe(true);
  expect((JSON.parse(readFileSync(OUT, 'utf8')) as { rows: Row[] }).rows).toEqual(rows);
  expect(rows.some((r) => r.index32)).toBe(true);
  expect(rows.some((r) => r.role === 'front')).toBe(true);
});
