/**
 * Golden-table generator for motion_jsmath — V8's `Math` bit for bit.
 *
 * RUNS Node's own `Math.*` (V8's fdlibm port) over a fixed, seeded corpus of
 * inputs and writes `golden_jsmath.inc`; then Number⇄String (toString,
 * toFixed, toPrecision, toExponential, toString(radix), Number(str)) into
 * `golden_numconv.inc`. The C++ suite
 * (`native/tests/test_jsmath.cpp`) checks every row with exact bit equality
 * (NaN == NaN, and -0 is not +0). Every value is written as its IEEE-754 bit
 * pattern in hex, so the table carries the bits and nothing is re-parsed.
 *
 * Regenerate (Node ≥ 22.6 strips the types itself):
 *
 *     node native/tests/gen_golden_jsmath.ts
 *
 * `JSMATH_SAMPLES=40000 NUMCONV_SAMPLES=700 node native/tests/gen_golden_jsmath.ts --out <file>`
 * writes a much larger table for a one-off soak (not committed; the port was
 * soaked at 40k inputs per Math function and 23k Number/String rows with zero
 * differences).
 *
 * Which V8 is the reference matters: the table header records
 * `process.versions.v8`. V8 has carried fdlibm since 2016; if a future V8
 * changes a routine, this table changes, and the C++ must follow.
 */

import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

// Stable ids — the C++ side switches on these (test_jsmath.cpp `call()`).
const UNARY: Array<[string, (x: number) => number]> = [
  ['sin', Math.sin], ['cos', Math.cos], ['tan', Math.tan],
  ['asin', Math.asin], ['acos', Math.acos], ['atan', Math.atan],
  ['exp', Math.exp], ['expm1', Math.expm1], ['log', Math.log],
  ['log1p', Math.log1p], ['log2', Math.log2], ['log10', Math.log10],
  ['sinh', Math.sinh], ['cosh', Math.cosh], ['tanh', Math.tanh],
  ['asinh', Math.asinh], ['acosh', Math.acosh], ['atanh', Math.atanh],
  ['cbrt', Math.cbrt], ['round', Math.round], ['sign', Math.sign],
  ['fround', Math.fround], ['clz32', Math.clz32],
];
const BINARY: Array<[string, (x: number, y: number) => number]> = [
  ['atan2', Math.atan2], ['pow', Math.pow], ['hypot2', (x, y) => Math.hypot(x, y)],
  ['imul', Math.imul], ['max2', (x, y) => Math.max(x, y)], ['min2', (x, y) => Math.min(x, y)],
  ['mod', (x, y) => x % y],
];

const argv = process.argv.slice(2);
const outArg = argv.indexOf('--out');
const PER_FN = Number(process.env.JSMATH_SAMPLES ?? 120);
const NUM_SAMPLES = Number(process.env.NUMCONV_SAMPLES ?? 220);

// xorshift64* — seeded, so the corpus is the same on every run.
let state = 0x9e3779b97f4a7c15n;
function nextU64(): bigint {
  state ^= state >> 12n;
  state ^= (state << 25n) & 0xffffffffffffffffn;
  state ^= state >> 27n;
  return (state * 0x2545f4914f6cdd1dn) & 0xffffffffffffffffn;
}
function uniform(): number {
  return Number(nextU64() >> 11n) / 2 ** 53;
}
const dv = new DataView(new ArrayBuffer(8));
function fromBits(b: bigint): number {
  dv.setBigUint64(0, b);
  return dv.getFloat64(0);
}
function hex(x: number): string {
  dv.setFloat64(0, x);
  return `0x${dv.getBigUint64(0).toString(16).padStart(16, '0')}ull`;
}

/** Inputs spanning every reduction branch: small, medium, huge, subnormal, specials. */
function inputFor(i: number): number {
  const kind = i % 8;
  const u = uniform();
  switch (kind) {
    case 0: return (u * 2 - 1) * 1.6;             // around the primary range
    case 1: return (u * 2 - 1) * 12;              // a few periods
    case 2: return (u * 2 - 1) * 1e4;             // wiggle-noise territory
    case 3: return (u * 2 - 1) * 2 ** 21;         // medium rem_pio2 (Cody-Waite)
    case 4: return fromBits(nextU64() & 0x7fefffffffffffffn) * (u < 0.5 ? 1 : -1); // any finite
    case 5: return u * 2;                         // [0, 2): log/acosh/atanh boundaries
    case 6: return (u * 2 - 1) * 720;             // exp overflow edge
    default: return (u * 2 - 1) * 0.02;           // tiny: series branches
  }
}

const SPECIAL = [
  0, -0, 1, -1, 0.5, -0.5, 2, -2, 3, 10, 0.1, Math.PI, -Math.PI, Math.PI / 2, Math.PI / 4,
  Math.E, 1e-300, -1e-300, 5e-324, -5e-324, 2.2250738585072014e-308, 1.7976931348623157e308,
  -1.7976931348623157e308, Infinity, -Infinity, NaN, 709.782712893384, -745.1332191019411,
  710.4758600739439, 22, 0.34657359027997264, 1.0397207708399179, 2 ** -28, 2 ** -54, 2 ** 31,
  2 ** 53, 2 ** 64, 1e21, 0.9999999999999999, 1.0000000000000002, 4.5, -4.5, 2.5, -2.5,
  0.49999999999999994, 1234567.89, 127.1, 43758.5453,
];

const lines: string[] = [
  '// GENERATED by native/tests/gen_golden_jsmath.ts — do not edit by hand.',
  '// Regenerate:  node native/tests/gen_golden_jsmath.ts',
  `// Reference: Node ${process.version}, V8 ${process.versions.v8}.`,
  '//',
  '// MOTION_JSMATH_1(name, x_bits, expected_bits) / MOTION_JSMATH_2(name, x_bits, y_bits, expected_bits):',
  '// IEEE-754 bit patterns of the inputs and of what V8 returned.',
  '',
];
let rows = 0;
for (const [name, fn] of UNARY) {
  const xs = [...SPECIAL];
  for (let i = 0; i < PER_FN; i++) xs.push(inputFor(i));
  for (const x of xs) {
    lines.push(`MOTION_JSMATH_1(${name}, ${hex(x)}, ${hex(fn(x))})`);
    rows++;
  }
}
for (const [name, fn] of BINARY) {
  const pairs: Array<[number, number]> = [];
  for (const a of SPECIAL) for (const b of [0, -0, 1, -1, 0.5, 2, -3, Infinity, -Infinity, NaN, 1e300]) pairs.push([a, b]);
  for (let i = 0; i < PER_FN; i++) {
    const x = inputFor(i);
    const y = name === 'pow'
      ? (i % 3 === 0 ? Math.round(inputFor(i + 1) % 40) : (uniform() * 2 - 1) * (i % 5 === 0 ? 400 : 8))
      : inputFor(i + 3);
    pairs.push([x, y]);
  }
  for (const [x, y] of pairs) {
    lines.push(`MOTION_JSMATH_2(${name}, ${hex(x)}, ${hex(y)}, ${hex(fn(x, y))})`);
    rows++;
  }
}
lines.push('');

const here = dirname(fileURLToPath(import.meta.url));
const out = outArg >= 0 ? argv[outArg + 1]! : join(here, 'golden_jsmath.inc');
writeFileSync(out, lines.join('\n'));
console.log(`wrote ${out}: ${rows} rows`);

// ── Number ⇄ String (golden_numconv.inc) ────────────────────────────────────

/** A C++ `u"…"` literal for any JS string (UTF-16 code units, escaped). */
function u16(s: string): string {
  let o = 'u"';
  for (let i = 0; i < s.length; i++) {
    const c = s.charCodeAt(i);
    if (c === 0x22 || c === 0x5c) o += `\\${s[i]}`;
    else if (c >= 0x20 && c < 0x7f && s[i] !== '?') o += s[i];
    else o += `\\u${c.toString(16).padStart(4, '0')}`;
  }
  return `${o}"`;
}

const NUMS: number[] = [
  0, -0, 1, -1, 0.1, 0.2, 0.1 + 0.2, 1 / 3, 2 / 3, 0.5, 1.5, 2.5, -2.5, 1.005, 1.45, 1.55, 8.345,
  1e21, 1e21 - 65536, 999999999999999900000, 1e-6, 1e-7, 1.5e-7, 123e-20, 5e-324, 2.2250738585072014e-308,
  1.7976931348623157e308, 2 ** 53, 2 ** 53 + 2, 2 ** 60, 2 ** 70, -(2 ** 70), 4.35, 0.000001, 1234.5678,
  NaN, Infinity, -Infinity, 100, 1e100, 123456789012345680000, 0.3, 25.5, 99.995, 9.995, 0.045, 1e-10,
  Math.PI, Math.E, 43758.5453, 127.1, 1013.7, 71.3, 0.0001, 12345678.9, 5.5e-10,
];
for (let i = 0; i < NUM_SAMPLES; i++) {
  const u = uniform();
  const k = i % 7;
  if (k === 0) NUMS.push((u - 0.5) * 2000);
  else if (k === 1) NUMS.push(Math.round((u - 0.5) * 1e6) / 100);  // cents: toFixed ties
  else if (k === 2) NUMS.push(fromBits(nextU64() & 0x7fefffffffffffffn));
  else if (k === 3) NUMS.push(u * 10 ** Math.floor(uniform() * 40 - 20));
  else if (k === 4) NUMS.push(Math.round(u * 1e4) / 8);         // exact binary fractions
  else if (k === 5) NUMS.push(-u * 1e-3);
  else NUMS.push(Math.floor((u - 0.5) * 2 ** 40));
}

const nl: string[] = [
  '// GENERATED by native/tests/gen_golden_jsmath.ts — do not edit by hand.',
  `// Reference: Node ${process.version}, V8 ${process.versions.v8}.`,
  '//',
  '// MOTION_NUM_TOSTRING(x_bits, str)        Number::toString(x)',
  '// MOTION_NUM_FIXED(x_bits, f, str)        x.toFixed(f)',
  '// MOTION_NUM_PRECISION(x_bits, p, str)    x.toPrecision(p)',
  '// MOTION_NUM_EXPONENTIAL(x_bits, f, str)  x.toExponential(f), f = -1 for undefined',
  '// MOTION_NUM_RADIX(x_bits, radix, str)    x.toString(radix)',
  '// MOTION_NUM_PARSE(str, bits)             Number(str)',
  '',
];
let nrows = 0;
const parseInputs: string[] = [
  '', ' ', '0', '-0', '+0', '.5', '5.', '.', '+.5', '-.5e3', '1e', '1e+', '1e-7', '1E3', '  12  ',
  ' 12﻿', ' -3.25　', '1_000', '0x1F', '0X1f', '-0x1F', '0x', '0o17', '0b101', '0b102',
  '0o8', 'Infinity', '-Infinity', '+Infinity', 'infinity', 'NaN', '12px', '1.2.3', '00012', '0012.50',
  '1e400', '-1e400', '1e-400', '2.4703282292062327e-324', '2.4703282292062328e-324', '4.9406564584124654e-324',
  '1.7976931348623158e308', '1.7976931348623159e308', '9007199254740993', '9007199254740995',
  '0.1000000000000000055511151231257827021181583404541015625', '0.30000000000000004',
  '123456789012345678901234567890', '0x1fffffffffffff', '0x20000000000001', '0x20000000000003',
  '0xfffffffffffffc00', '\n\t42\r\n', '1e1000000000', '3.14abc', '٣', '1,5',
];
for (const x of NUMS) {
  nl.push(`MOTION_NUM_TOSTRING(${hex(x)}, ${u16(String(x))})`);
  nrows++;
  for (const f of [0, 2, 5, 20]) {
    nl.push(`MOTION_NUM_FIXED(${hex(x)}, ${f}, ${u16(x.toFixed(f))})`);
    nrows++;
  }
  for (const p of [1, 3, 17, 21]) {
    nl.push(`MOTION_NUM_PRECISION(${hex(x)}, ${p}, ${u16(x.toPrecision(p))})`);
    nrows++;
  }
  for (const f of [-1, 0, 4, 20]) {
    nl.push(`MOTION_NUM_EXPONENTIAL(${hex(x)}, ${f}, ${u16(f < 0 ? x.toExponential() : x.toExponential(f))})`);
    nrows++;
  }
  for (const r of [2, 16, 36]) {
    nl.push(`MOTION_NUM_RADIX(${hex(x)}, ${r}, ${u16(x.toString(r))})`);
    nrows++;
  }
  parseInputs.push(String(x), x.toPrecision(19));
}
for (let i = 0; i < NUM_SAMPLES; i++) {
  // Long random digit strings: the correctly-rounded parse path.
  let s = '';
  const n = 1 + Math.floor(uniform() * 40);
  for (let j = 0; j < n; j++) s += String(Math.floor(uniform() * 10));
  if (uniform() < 0.5) s = `${s.slice(0, 1)}.${s.slice(1)}`;
  if (uniform() < 0.7) s += `e${Math.floor(uniform() * 700 - 350)}`;
  parseInputs.push(s);
}
for (const s of parseInputs) {
  nl.push(`MOTION_NUM_PARSE(${u16(s)}, ${hex(Number(s))})`);
  nrows++;
}
nl.push('');
const numOut = outArg >= 0 ? `${argv[outArg + 1]!}.numconv.inc` : join(here, 'golden_numconv.inc');
writeFileSync(numOut, nl.join('\n'));
console.log(`wrote ${numOut}: ${nrows} rows`);
