/**
 * Golden-table generator for the motion_eval bit-identity contract.
 *
 * Runs the TypeScript sampler (`packages/animation/src/interpolate.ts`) — the
 * reference implementation the C++ port must match — over a fixed 3-keyframe
 * bezier track and emits `golden_bezier.inc`, an X-macro file that BOTH the
 * Catch2 suite (`native/tests/test_eval.cpp`) and the TypeScript bridge test
 * (`packages/native-bridge/src/bridge.test.ts`) consume. One file, one truth.
 *
 * Regenerate (from the repo root, Node ≥ 22.6 strips the types itself; the
 * only import is `import type`, which is erased, so no bundler is needed):
 *
 *     node native/tests/gen_golden.ts
 *
 * Numbers are printed with JavaScript's shortest round-trip representation,
 * which parses back to the exact same double in C++ (`strtod` is correctly
 * rounded) — so the table carries the bits, not a decimal approximation.
 *
 * The track deliberately exercises every branch of `sampleTrack` that the
 * scalar ABI covers: a CSS-style bezier segment, an overshooting bezier
 * segment (y handles outside 0..1), the before/at/after clamps, a sample
 * exactly on the interior keyframe, and the spatial-tangent 1D cubic on the
 * second segment (`so` on keyframe 1, `si` on keyframe 2).
 */

import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { sampleTrack } from '../../packages/animation/src/interpolate.ts';
import type { Keyframe, PropertyTrack } from '../../packages/animation/src/types.ts';

// ── The packed representation (mirror of include/motion/motion_eval.h) ─────
// These numbers are the ABI. If they change there, they change here and in
// packages/native-bridge/src/packed.ts; `abi_pinned.test.ts` checks the mirror.
const EASING = {
  linear: 0,
  hold: 1,
  bezier: 2,
  easeIn: 3,
  easeOut: 4,
  easeInOut: 5,
  ease: 6,
  autoBezier: 7,
  continuousBezier: 8,
  step: 9,
} as const;
const FLAG_HAS_BEZIER = 1;
const FLAG_HAS_SI = 2;
const FLAG_HAS_SO = 4;
const SPATIAL_SHIFT = 4;
const SPATIAL = { linear: 1, bezier: 2, continuous: 3, auto: 4 } as const;

const keyframes: Keyframe[] = [
  { t: 0, value: 0, easing: 'bezier', bezier: [0.42, 0, 0.58, 1] },
  { t: 1, value: 100, easing: 'bezier', bezier: [0.17, 0.67, 0.83, 0.67], so: 30 },
  { t: 2.5, value: -40, si: -12.5 },
];
const track: PropertyTrack = { nodeId: 'golden', prop: 'x', keyframes };

const times = [
  -1, 0, 0.05, 0.1, 0.2, 0.25, 0.333, 0.4, 0.5, 0.6, 0.75, 0.9, 0.99,
  1, 1.1, 1.25, 1.5, 1.75, 2, 2.2, 2.4, 2.4999, 2.5, 3,
];

function flagsOf(k: Keyframe): number {
  let f = 0;
  if (k.bezier !== undefined) f |= FLAG_HAS_BEZIER;
  if (k.si !== undefined) f |= FLAG_HAS_SI;
  if (k.so !== undefined) f |= FLAG_HAS_SO;
  if (k.spatialInterp !== undefined) f |= SPATIAL[k.spatialInterp] << SPATIAL_SHIFT;
  return f;
}

const lines: string[] = [
  '// GENERATED by native/tests/gen_golden.ts — do not edit by hand.',
  '// Regenerate:  node native/tests/gen_golden.ts',
  '//',
  '// X-macro table. Define MOTION_GOLDEN_KF(t, value, easing, flags, c0, c1, c2, c3, si, so)',
  '// and MOTION_GOLDEN_SAMPLE(t, expected) before including. Values are the exact',
  '// doubles produced by packages/animation/src/interpolate.ts sampleTrack().',
  '',
];
for (const k of keyframes) {
  const [c0, c1, c2, c3] = k.bezier ?? [0, 0, 0, 0];
  const easing = EASING[k.easing ?? 'linear'];
  lines.push(
    `MOTION_GOLDEN_KF(${k.t}, ${k.value}, ${easing}, ${flagsOf(k)}, ${c0}, ${c1}, ${c2}, ${c3}, ${k.si ?? 0}, ${k.so ?? 0})`,
  );
}
lines.push('');
for (const t of times) {
  const v = sampleTrack(track, t);
  if (v === undefined || Number.isNaN(v)) throw new Error(`sampleTrack returned ${v} at t=${t}`);
  lines.push(`MOTION_GOLDEN_SAMPLE(${t}, ${v})`);
}
lines.push('');

const here = dirname(fileURLToPath(import.meta.url));
const out = join(here, 'golden_bezier.inc');
writeFileSync(out, lines.join('\n'));
console.log(`wrote ${out}: ${keyframes.length} keyframes, ${times.length} samples`);
